### ISSUE TITLE
ModuleNotFoundError: No module named 'elftools'  AttributeError : module 'pwndbg' has no attribute 'color'

### ISSUE THREAD

**Issue by bufferflyfly** [pwndbg/pwndbg#945] opened 2021-08-13 07:08 UTC

**Comment by bufferflyfly** [comment] 2021-08-13 07:12
./setup.sh can run normal. However, when I run gdb, this error appeared. I installed elftools by pip, but it was not worked. How I do can solve it? Please help me

**Comment by disconnect3d** [comment] 2021-08-20 02:54
Hey, since there is not much information from your side, I am going to close this issue. Please provide more information so the issue can be reproduced next time (OS, steps you did, etc; it would be neat if this can be easily reproduced e.g. in a standard docker container, but if not, its also ok).

**Closed as completed by disconnect3d** 2021-08-20 02:54 UTC
Labels: invalid
