### ISSUE TITLE
Feature: piebase as vars (ie. $piebase, $rva)

### ISSUE THREAD

**Issue by syndrill** [pwndbg/pwndbg#592] opened 2019-01-29 16:05 UTC
Would be nice to have this in feature lists. I always do this manually by using 
```gdb
set $rva = some_offset
```
Then accessing .bss or other relative offset, with
```gdb
x/8gx  $rva+some_other_offset
```

**Comment by syndrill** [comment] 2019-01-31 07:48
I'm kind of new to this project. Is there any part of this to look at first? There are some implementations I have been thinking,
1. by executing `set $rva = some_offset` every `piebase` command executed, this can't be foolproof though. What will happen when ASLR activated and program restarted?
ref: https://github.com/scwuaptx/Pwngdb/blob/master/pwndbg/pwngdb.py#L72
2. by executing `set $rva = some_offset` every some "events", like when restart executable or first run.

**Comment by disconnect3d** [comment] 2019-02-03 04:29
Hey, although we have this kind of feature as a gdb function (e.g. `p/x $rebase(0x1234)` and also `breakrva 0x1234` as for setting a breakpoint), I still find it useful (and it should probably make the `$rebase` function obsolete/deprecated).

This should be set within a program start event, so you must write a function and decorate it with `pwndbg.events.start` as in https://github.com/pwndbg/pwndbg/blob/71d29df0498e4584db99015964f1722664e62824/pwndbg/argv.py#L28-L34.

The base address itself can be retrieved the same as in https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/gdbutils/functions.py#L53

PS: Sorry for the late reply, I have been on vacation ;).

**Comment by disconnect3d** [comment] 2019-04-21 13:46
@zeroload Hey, are you going to work on this?

**Comment by syndrill** [comment] 2019-04-23 13:29
> @zeroload Hey, are you going to work on this?

Uh.. yeah. I totally forgot about this. Sorry, I don't think I could work on this.

**Comment by gsingh93** [comment] 2022-10-03 02:25
Accidentally made a duplicate of this, but let's keep discussing it there: https://github.com/pwndbg/pwndbg/issues/1144

**Closed as completed by gsingh93** 2022-10-03 02:25 UTC
Labels: help wanted, feature, good first issue
