### ISSUE TITLE
Exception when some primitive types are not defined in the debuginfo

### ISSUE THREAD

**Issue by bjorn3** [pwndbg/pwndbg#742] opened 2020-04-24 14:53 UTC
https://github.com/pwndbg/pwndbg/blob/fbd2bb3abfc2500aae76d159e23015008e879b8d/pwndbg/typeinfo.py#L37-L43

It should just silently ignore the missing primitive types.

```
Exception occurred: Error: No type named uint32. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'gdb.error'> No type named uint32.:
```

**Comment by disconnect3d** [comment] 2020-04-26 13:24
...and return None and this should be handled by callers of this func?

**Comment by disconnect3d** [comment] 2020-06-07 16:48
@bjorn3 do u have any binary that can be used to reproduce this?

**Comment by disconnect3d** [comment] 2020-06-07 17:00
Can be reproduced via:
```
pwndbg> set language unknown
pwndbg> entry
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/events.py", line 169, in caller
    func()
  File "/opt/pwndbg/pwndbg/typeinfo.py", line 52, in update
    module.ulong  = lookup_types('unsigned long', 'uint', 'u32', 'uint32')
  File "/opt/pwndbg/pwndbg/typeinfo.py", line 43, in lookup_types
    raise exc
  File "/opt/pwndbg/pwndbg/typeinfo.py", line 40, in lookup_types
    return gdb.lookup_type(type_str)
gdb.error: No type named uint32.
```

**Comment by disconnect3d** [comment] 2020-06-07 17:02
Uh, what shall we do here? We could save current language, set lang to C, grab types and bring back the proper language. This will probably work to fetch types with given size, but I am not sure if that's what we want?

Just to clarify: we can't instantiate type objects from GDB >_<

**Comment by disconnect3d** [comment] 2020-06-07 17:02
@zachriggle any opinion here?

**Comment by nankeen** [comment] 2020-07-21 21:20
Another example: this was compiled with `rustc -g example.rs` and throws a similar error.

```rust
fn main() {
    println!("Hello world");
}
```

```
Exception occurred: Error: No type named int16. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
Python Exception <class 'gdb.error'> No type named int16.:
```

But the following isn't raising an exception for me:
```rust
fn main() {
    let _a = 0i16;
    let _b = 0i64;
    println!("Hello world!");
}
```

Working around this with `set language c`.

Any updates on the intended fix?

**Comment by zachriggle** [comment] 2020-07-22 04:50
I think the workaround for this is to find out which type *IS* declared for the equivalent of `uint16_t` and make it an alias in the typeinfo module.  @disconnect3d do you know how to dump the available types?

**Comment by nankeen** [comment] 2020-07-22 23:41
I don't think there's a direct way to dump available equivalent types directly through gdb's python API. The type information seems to come from https://github.com/bminor/binutils-gdb/blob/gdb-8.1-branch/gdb/symtab.c#L2092 which depends on the language.

For rust, this is the function that tries to find the global symbol: https://github.com/bminor/binutils-gdb/blob/gdb-8.1-branch/gdb/rust-lang.c#L2187 which causes this error if it's not included by the compiler.

For C it's this: https://github.com/bminor/binutils-gdb/blob/gdb-8.1-branch/gdb/symtab.c#L2092

However the latter would lookup architecture primitives, the former only searches symbols. So I think the only way to get a equivalent type might be to change the language. 😕 (?)

**Comment by disconnect3d** [comment] 2023-01-04 01:32
This should be fixed for Rust binaries with https://github.com/pwndbg/pwndbg/pull/1495

I think we should eventually build the types ourselves after GDB adds a way to create types with Python API (a coworker of mine works on adding that support, so we have it in GDB 13.x).

Closing this as we don't have a counter example that triggers this anymore

**Closed as completed by disconnect3d** 2023-01-04 01:32 UTC
Labels: bug
