### ISSUE TITLE
Faster vis -a or print ongoing 

### ISSUE THREAD

**Issue by yooo1999** [pwndbg/pwndbg#1675] opened 2023-04-19 19:09 UTC
When I want to print all of heap in current arena I use
`vis -s` 

That work, but if the arena is big enough that command can takes 15-20 minutes!

Please try to do it faster, that very slow , or do not wait until the code finish all arena and print while the result (ongoing the analyze )

**Comment by disconnect3d** [comment] 2023-04-19 20:01
Is there any reason why are you printing the whole arena this way? What do you want to achieve? If this is more some analysis, you should probably read the memory yourself with `pwndbg.gdblib.memory.read(...)` and analyze it with additional code.

**Comment by disconnect3d** [comment] 2023-04-19 20:03
But anyway, if you can create an example where it takes e.g. 1-5 min to print all heap, I can try to benchmark it and see if we can optimize it.

**Comment by disconnect3d** [comment] 2023-04-19 20:04
Alternatively, we can definetely print it ongoing with some flag maybe: that is super easy to implement.

**Comment by yooo1999** [comment] 2023-04-19 20:33
@disconnect3d if arena size is about 0x10000 size with lot of allocation and free it's take lot of time 
I need to print that for some analyze of all the heap

**Comment by disconnect3d** [comment] 2023-04-19 20:42
I assume this is you work since you ask many questions about those topics; is there any chance you can contribute to those areas of your interests? :)

We could either have a flag like `-o | --ongoing` that would make it so that instead of appending to the `out` string (in the `vis_heap_chunks` function in `commands/heap.py`) we would `print` it immediately, or, we could work on benchmarking and improving the speed of all this.

The benchmarking can be done with standard Python tools for that and we also have some utility functions for that. You can do:
```py
pwndbg.profiling.profiler.start()
<execute some code>
pwndbg.profiling.profiler.stop()
```
which should save a profile file in the directory you started GDB from. Then, you can read the profile like this:
```
python3 <path-to-pwndbg>/profiling/print_stats.py <profile-file>
```

Ideally, since you probably don't want to wait 10-20min, you can change `vis_heap_chunks` command to break its string creation loop e.g. when it gets X results, so that we can benchmark e.g. 30s of execution instead of 10min.

**Comment by disconnect3d** [comment] 2023-04-19 20:49
Here's an example profile from `vis -a` command generated by `source script.py`:
```py
import gdb, pwndbg

pwndbg.profiling.profiler.start()
gdb.execute("vis -a", to_string=True)
pwndbg.profiling.profiler.stop()
```

Report:
```
$ python3 ../pwndbg/profiling/print_stats.py ./pwndbg-1681937259.pstats
Wed Apr 19 21:47:39 2023    ./pwndbg-1681937259.pstats

         24929221 function calls (24913554 primitive calls) in 9.356 seconds

   Ordered by: cumulative time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    0.000    0.000    9.356    9.356 {built-in method _gdb.execute}
        1    0.000    0.000    9.355    9.355 __init__.py:128(invoke)
        1    0.000    0.000    9.355    9.355 __init__.py:182(__call__)
        1    0.000    0.000    9.355    9.355 __init__.py:317(_OnlyWhenRunning)
        1    0.000    0.000    9.354    9.354 __init__.py:394(_OnlyWithResolvedHeapSyms)
        1    0.000    0.000    9.348    9.348 __init__.py:358(_try2run_heap_command)
        1    0.000    0.000    9.348    9.348 __init__.py:342(_OnlyWhenHeapIsInitialized)
        1    0.400    0.400    9.347    9.347 heap.py:823(vis_heap_chunks)
    49435    4.477    0.000    6.361    0.000 heap.py:982(bin_labels)
    49435    0.711    0.000    1.207    0.000 heap.py:975(bin_ascii)
    98872    0.210    0.000    0.727    0.000 memory.py:18(read)
  3213288    0.699    0.000    0.699    0.000 {method 'format' of 'str' objects}
  9689260    0.668    0.000    0.668    0.000 {built-in method builtins.hex}
  9764888    0.599    0.000    0.612    0.000 {built-in method builtins.isinstance}
    98872    0.462    0.000    0.462    0.000 {method 'read_memory' of 'gdb.Inferior' objects}
    49451    0.064    0.000    0.417    0.000 {method 'join' of 'str' objects}
   444915    0.341    0.000    0.353    0.000 heap.py:979(<genexpr>)
     1299    0.002    0.000    0.176    0.000 ptmalloc.py:310(is_top_chunk)
    74152    0.044    0.000    0.175    0.000 __init__.py:138(wrapper)
     1299    0.001    0.000    0.165    0.000 ptmalloc.py:303(arena)
     1299    0.001    0.000    0.164    0.000 ptmalloc.py:296(heap)
     1301    0.009    0.000    0.164    0.000 ptmalloc.py:346(__init__)
    74152    0.045    0.000    0.102    0.000 __init__.py:125(colorize)
    49435    0.017    0.000    0.079    0.000 <frozen importlib._bootstrap>:997(_handle_fromlist)
     1302    0.013    0.000    0.070    0.000 ptmalloc.py:1457(get_sbrk_heap_region)
    49435    0.042    0.000    0.069    0.000 arch.py:37(unpack)
     3898    0.007    0.000    0.067    0.000 ptmalloc.py:173(__match_renamed_field)
     2600    0.020    0.000    0.065    0.000 ptmalloc.py:195(size)
    50749    0.063    0.000    0.063    0.000 {built-in method builtins.hasattr}
     7796    0.009    0.000    0.060    0.000 types.py:44(has_field)
    74152    0.031    0.000    0.057    0.000 __init__.py:185(terminateWith)
     7796    0.047    0.000    0.047    0.000 {method 'fields' of 'gdb.Type' objects}
     3902    0.015    0.000    0.044    0.000 ptmalloc.py:151(__init__)
     1302    0.002    0.000    0.042    0.000 ptmalloc.py:1067(get_region)
18170/18161    0.011    0.000    0.039    0.000 memoize.py:43(__call__)
16926/1302    0.015    0.000    0.038    0.000 copy.py:132(deepcopy)
     1298    0.012    0.000    0.035    0.000 ptmalloc.py:205(real_size)
     1299    0.003    0.000    0.034    0.000 ptmalloc.py:247(prev_inuse)
    18891    0.008    0.000    0.033    0.000 __init__.py:69(purple)
    16437    0.007    0.000    0.030    0.000 __init__.py:65(blue)
    16860    0.007    0.000    0.030    0.000 __init__.py:57(green)
    98872    0.029    0.000    0.029    0.000 {built-in method _gdb.selected_inferior}
    50737    0.028    0.000    0.028    0.000 ptmalloc.py:518(top)
     1302    0.004    0.000    0.027    0.000 copy.py:268(_reconstruct)
    49435    0.027    0.000    0.027    0.000 {built-in method _struct.unpack}
    98873    0.027    0.000    0.027    0.000 {built-in method builtins.max}
    74159    0.026    0.000    0.026    0.000 {method 'replace' of 'str' objects}
     6766    0.011    0.000    0.024    0.000 memory.py:292(poi)
   247175    0.022    0.000    0.022    0.000 {method 'keys' of 'collections.OrderedDict' objects}
     1304    0.003    0.000    0.021    0.000 ptmalloc.py:1329(main_arena)
    11481    0.004    0.000    0.021    0.000 __init__.py:73(cyan)
    10483    0.004    0.000    0.019    0.000 __init__.py:61(yellow)
     1431    0.005    0.000    0.015    0.000 ptmalloc.py:450(__init__)
     1302    0.003    0.000    0.015    0.000 copy.py:236(_deepcopy_dict)
    18170    0.007    0.000    0.013    0.000 abc.py:180(__instancecheck__)
    91616    0.012    0.000    0.012    0.000 {built-in method builtins.chr}
     1308    0.002    0.000    0.010    0.000 ptmalloc.py:1392(mp)
        2    0.000    0.000    0.009    0.004 {built-in method builtins.print}
        6    0.000    0.000    0.009    0.001 __init__.py:47(write)
        6    0.009    0.001    0.009    0.001 {built-in method _gdb.write}
        7    0.000    0.000    0.008    0.001 typeinfo.py:92(load)
        8    0.008    0.001    0.008    0.001 {built-in method _gdb.lookup_type}
    49443    0.007    0.000    0.007    0.000 {method 'extend' of 'list' objects}
     6768    0.007    0.000    0.007    0.000 {method 'dereference' of 'gdb.Value' objects}
        2    0.000    0.000    0.007    0.003 ptmalloc.py:1316(libc_has_debug_syms)
    18170    0.006    0.000    0.006    0.000 _weakrefset.py:70(__contains__)
      126    0.001    0.000    0.005    0.000 ptmalloc.py:1151(bin_at)
        1    0.001    0.001    0.005    0.005 ptmalloc.py:1120(tcachebins)
     7796    0.004    0.000    0.005    0.000 types.py:22(get_basic_type)
     6768    0.005    0.000    0.005    0.000 {method 'cast' of 'gdb.Value' objects}
        4    0.000    0.000    0.004    0.001 symbol.py:112(address)
        4    0.004    0.001    0.004    0.001 {built-in method _gdb.lookup_symbol}
        1    0.000    0.000    0.004    0.004 ptmalloc.py:1091(fastbins)
        2    0.000    0.000    0.003    0.002 glibc.py:183(_OnlyWhenGlibcLoaded)
      8/4    0.000    0.000    0.003    0.001 proc.py:154(wrapper)
        4    0.000    0.000    0.003    0.001 glibc.py:37(get_version)
        1    0.000    0.000    0.003    0.003 glibc.py:51(_get_version)
    35155    0.003    0.000    0.003    0.000 {method 'get' of 'dict' objects}
        1    0.000    0.000    0.003    0.003 ptmalloc.py:1216(smallbins)
<truncated>
```

**Comment by disconnect3d** [comment] 2023-04-19 21:11
Ok, a nice way to reproduce the benchmark is e.g.:
```
gdb --ex 'break exit' --ex 'run' --ex 'source s.py' --args `which python3` -c 'import sys; sys.exit(0)'
```

**Comment by disconnect3d** [comment] 2023-04-19 21:48
@yooo1999 I did some investigations and found out we execute `bin_labels` way too much and that its results can be precalculated.

I am still waiting for tests to pass on CI, but please also see if it actually speeds up things for you and by how much: https://github.com/pwndbg/pwndbg/pull/1678 since my quick benchmarking shows it should optimize things very much :)

**Comment by yooo1999** [comment] 2023-04-20 18:32
@disconnect3d Thank you ! I will try, but right now even with your fix when I tried to run vis to the remote device that not print anything even if I wait 1 hour,
I try to figure it out

**Comment by yooo1999** [comment] 2023-04-23 21:03
@disconnect3d very hard to debug it because now I see `vis` does not print anything , just wait forever (with or without you PR)
I do not know how to check it.
Maybe print some verbose log or another idea

**Comment by yooo1999** [comment] 2023-04-23 21:31
I run profile now , that take about 400 seconds to parse the heap using `vis -a` (I add some printing)
`len(chunk_delims)=33` [here](https://github.com/pwndbg/pwndbg/blob/7720b81cc753cf33f7ec4515dfa1321a2131763d/pwndbg/commands/heap.py#L917) was 33

When I analyzed the results I saw
```

ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    13754    0.329    0.000  381.755    0.028 memory.py:18(read)
    13754  381.324    0.028  381.324    0.028 {method 'read_memory' of 'gdb.Inferior' objects}
      126    0.008    0.000    7.238    0.057 ptmalloc.py:1151(bin_at)
      252    6.618    0.026    7.192    0.029 ptmalloc.py:1184(<lambda>)
        1    0.000    0.000    5.950    5.950 ptmalloc.py:1722(thread_arena)
       32    0.001    0.000    4.461    0.139 ptmalloc.py:310(is_top_chunk)
       33    0.945    0.029    3.835    0.116 ptmalloc.py:346(__init__)
        1    0.003    0.003    3.761    3.761 ptmalloc.py:1216(smallbins)
       32    0.000    0.000    3.649    0.114 ptmalloc.py:303(arena)
       32    0.000    0.000    3.649    0.114 ptmalloc.py:296(heap)
        1    0.003    0.003    3.385    3.385 ptmalloc.py:1230(largebins)
        1    0.000    0.000    2.901    2.901 ptmalloc.py:1648(prompt_for_tls_address)
```
This [line](https://github.com/pwndbg/pwndbg/blob/7720b81cc753cf33f7ec4515dfa1321a2131763d/pwndbg/commands/heap.py#L943) called 6800 times
read_memory take all of time .
Maybe we should read the arena to RAN and then parse it locally .

Thank you about your help!

**Comment by disconnect3d** [comment] 2023-05-02 03:21
@yooo1999 Just to be sure, does it mean that the #1678 speed up your case to 6-7 mintues from 15-20 minutes?

In regards to your last profiling, so it is now the memory reads that are so slow:
>    13754  381.324    0.028  381.324    0.028 {method 'read_memory' of 'gdb.Inferior' objects}

And it seems we really need to call them here:
https://github.com/pwndbg/pwndbg/blob/7720b81cc753cf33f7ec4515dfa1321a2131763d/pwndbg/commands/heap.py#L927-L943

Btw is your target an embedded device? Android? Is this run via GDB or GDB that connects to GDBServer?

Its hard to tell if we can speed up this but one we can try. Here are some things we can try to do:
1) We can try to read the whole memory page at once into Python and offset on that. This would work on both GDB and GDBServer but if that memory region is huge (e.g. megabytes or gigabytes) this would take lots of memory and may be slower.
2) We can try to map the `/proc/$pid/mem` file and map the memory into the GDB process, but I think we can't do it over gdbserver.

**Comment by disconnect3d** [comment] 2023-05-02 03:23
Omg we also read the memory twice: https://github.com/pwndbg/pwndbg/blob/7720b81cc753cf33f7ec4515dfa1321a2131763d/pwndbg/commands/heap.py#L943-L953

This can be easily optimized by saving the `read(cursor, ptr_size)` result into a variable and reusing that variable. At least this should optimize your case of:
>     13754  381.324    0.028  381.324    0.028 {method 'read_memory' of 'gdb.Inferior' objects}
to use 2x less read calls. No idea if this is going to actually improve the result since it may be that GDB caches that read_memory call but who knows.

**Comment by disconnect3d** [comment] 2023-05-02 03:27
@yooo1999 I have rebased https://github.com/pwndbg/pwndbg/pull/1678 and added the optimization mentioned in the previous post. Please retry!

**Comment by yooo1999** [comment] 2023-05-02 20:00
@disconnect3d That great !
when `len(chunk_delims) =39` I tried to run the new vis and old vis with profile :

new:
         320754 function calls (318105 primitive calls) in 12.362 seconds

   Ordered by: cumulative time

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     1162    0.019    0.000    6.474    0.006 memory.py:18(read)
     1162    6.449    0.006    6.449    0.006 {method 'read_memory' of 'gdb.Inferior' objects}
        1    0.000    0.000    2.026    2.026 ptmalloc.py:1714(thread_arena)
      126    0.006    0.000    1.665    0.013 ptmalloc.py:1143(bin_at)
      252    1.559    0.006    1.632    0.006 ptmalloc.py:1176(<lambda>)
       38    0.001    0.000    1.272    0.033 ptmalloc.py:310(is_top_chunk)
        2    1.190    0.595    1.191    0.595 {built-in method builtins.input}
       39    0.222    0.006    1.110    0.028 ptmalloc.py:346(__init__)
       38    0.000    0.000    1.041    0.027 ptmalloc.py:303(arena)
       38    0.000    0.000    1.041    0.027 ptmalloc.py:296(heap)
```


old:

         402093 function calls (397062 primitive calls) in 30.844 seconds

   Ordered by: cumulative time

```
   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
     3450    0.059    0.000   21.363    0.006 memory.py:18(read)
     3450   21.288    0.006   21.288    0.006 {method 'read_memory' of 'gdb.Inferior' objects}
      252    0.012    0.000    3.339    0.013 ptmalloc.py:1143(bin_at)
      504    3.160    0.006    3.274    0.006 ptmalloc.py:1176(<lambda>)
       76    0.001    0.000    2.422    0.032 ptmalloc.py:310(is_top_chunk)
       78    0.399    0.005    2.086    0.027 ptmalloc.py:346(__init__)
        2    0.000    0.000    2.026    1.013 ptmalloc.py:1714(thread_arena)
       76    0.000    0.000    2.000    0.026 ptmalloc.py:303(arena)
       76    0.001    0.000    2.000    0.026 ptmalloc.py:296(heap)
```

Is there any way to do it faster ? , maybe read all the arena once and then parse instead of reading each time 4 bytes?

**Comment by disconnect3d** [comment] 2023-05-12 09:08
Yes, I am pretty sure we can get this to be 5-10 or maybe even 20% faster without touching the reads. And as you say, we can also experiment with the reads to see if it gets faster or not if we read more data with less calls.

**Comment by disconnect3d** [comment] 2023-05-12 21:27
Things got slightly improved in https://github.com/pwndbg/pwndbg/pull/1708

**Comment by yooo1999** [comment] 2023-06-01 09:27
@disconnect3d Thank you , that really faster
But still I this we need to print that ongoing (like heap` command and not wait for the end of parsing

**Comment by disconnect3d** [comment] 2023-11-02 02:42
The `vis` command has been optimized as part of the discussion here.

If anyone wants to improve it further, please work on it and open a PR.

I am closing this issue since I don't think it needs to be prioritized by us.

If anyone steps under this issue once more, please create another issue or ideally, send a PR that improves this.

**Closed as completed by disconnect3d** 2023-11-02 02:42 UTC
Labels: enhancement
