### ISSUE TITLE
context in attached process gives TypeError: argument of type 'NoneType' is not iterable

### ISSUE THREAD

**Issue by tyilo** [pwndbg/pwndbg#867] opened 2020-12-14 12:04 UTC
### Description

When running `context` in an attached process I get the following error:
```
Traceback (most recent call last):
  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/usr/share/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/usr/share/pwndbg/pwndbg/commands/context.py", line 334, in context
    result[target].extend(func(target=out,
  File "/usr/share/pwndbg/pwndbg/commands/context.py", line 408, in context_regs
    regs = get_regs()
  File "/usr/share/pwndbg/pwndbg/commands/context.py", line 457, in get_regs
    m = ' ' * len(change_marker) if reg not in changed else C.register_changed(change_marker)
TypeError: argument of type 'NoneType' is not iterable
```

### Steps to reproduce

Create a process and attach to it:
```
$ sleep 10000 &
[2] 282936
$ gdb -p 282936
```

Then the error from above will occur.

### Possible fix

Changing
https://github.com/pwndbg/pwndbg/blob/9250cc51d8ef6cb872e66dcdc48f721d25aec582/pwndbg/commands/context.py#L440

to

```python
changed = pwndbg.regs.changed or []
```

seems to fix the problem for me.

### My setup

Platform: Linux-5.9.13-arch1-1-x86_64-with-glibc2.32
Gdb:      10.1
Python:   3.9.0 (default, Oct  7 2020, 23:09:01)  [GCC 10.2.0]
Pwndbg:   1.1.0
Capstone: 4.0.1024
Unicorn:  1.0.1
This GDB was configured as follows:
   configure --host=x86_64-pc-linux-gnu --target=x86_64-pc-linux-gnu
             --with-auto-load-dir=$debugdir:$datadir/auto-load
             --with-auto-load-safe-path=$debugdir:$datadir/auto-load
             --with-expat
             --with-gdb-datadir=/usr/share/gdb (relocatable)
             --with-jit-reader-dir=/usr/lib/gdb (relocatable)
             --without-libunwind-ia64
             --with-lzma
             --without-babeltrace
             --without-intel-pt
             --with-mpfr
             --without-xxhash
             --with-python=/usr (relocatable)
             --with-python-libdir=/usr/lib (relocatable)
             --with-debuginfod
             --with-guile
             --enable-source-highlight
             --with-separate-debug-dir=/usr/lib/debug (relocatable)
             --with-system-gdbinit=/etc/gdb/gdbinit

("Relocatable" means the directory can be moved with the GDB installation
tree, and GDB will still find it.)

**Comment by disconnect3d** [comment] 2020-12-14 15:43
Interesting, works for me on GDB `GNU gdb (Ubuntu 8.2-0ubuntu1~18.04) 8.2`. Wonder if 10.x changed something in this regard..

**Comment by tyilo** [comment] 2020-12-14 15:44
Or maybe this is caused by python 3.9?

**Comment by echo-Mike** [comment] 2020-12-19 13:05
Same error. Stock GDB in Ubuntu 20.10 with clean pwngdb setup (latest release) gives this exception on start or when trying to call ctx command
```
pwndbg> ctx
'context': Print out the current register, instruction, and stack context.
Exception occurred: context: argument of type 'NoneType' is not iterable (<class 'TypeError'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> ctx
'context': Print out the current register, instruction, and stack context.
Traceback (most recent call last):
  File "/home/ecmid/pwndbg/pwndbg/commands/__init__.py", line 136, in __call__
    return self.function(*args, **kwargs)
  File "/home/ecmid/pwndbg/pwndbg/commands/__init__.py", line 227, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/ecmid/pwndbg/pwndbg/commands/context.py", line 338, in context
    result[target].extend(func(target=out,
  File "/home/ecmid/pwndbg/pwndbg/commands/context.py", line 361, in context_regs
    return banner + get_regs() if with_banner else get_regs()
  File "/home/ecmid/pwndbg/pwndbg/commands/context.py", line 404, in get_regs
    m = ' ' * len(change_marker) if reg not in changed else C.register_changed(change_marker)
TypeError: argument of type 'NoneType' is not iterable

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
pwndbg>
```

**Comment by echo-Mike** [comment] 2020-12-19 13:07
Proposed fix works fine for me. Except that in release 2020.07.23 this was line 387
EDIT:
Seems like pwngdb must be loaded before start of program

**Comment by disconnect3d** [comment] 2021-01-03 07:59
> Seems like pwngdb must be loaded before start of program

Yeah, it seems so. Did u step on this bug *without* loading pwndbg before program start?

> Proposed fix works fine for me

If I apply the `changed = pwndbg.regs.changed or []` fix, I get an error in another place, if I load pwndbg after program start.

**Comment by echo-Mike** [comment] 2021-01-03 10:09
@disconnect3d
> Yeah, it seems so. Did u step on this bug without loading pwndbg before program start?

Yes. Even with fix applied
> If I apply the changed = pwndbg.regs.changed or [] fix, I get an error in another place, if I load pwndbg after program start.

I have similar error `'NoneType' is not iterable` but I do not remember the place

**Comment by disconnect3d** [comment] 2021-01-04 10:19
So to sum up, there seems to be an issue with order of operation/events firing when we load pwndbg in the middle of debugging.

Is the flow of loading pwndbg in the middle of debugging important to you folks? I personally used that flow maybe few times, but I can look at this more if it is something the community wants :P.

**Comment by disconnect3d** [comment] 2021-08-04 03:16
The bug with loading pwndbg after attaching is fixed with https://github.com/pwndbg/pwndbg/commit/b9e7bf1a756d82e49c49941904b9e42c278f0f58

**Closed as completed by disconnect3d** 2021-08-04 03:16 UTC
Labels: bug

**Comment by disconnect3d** [comment] 2021-08-04 03:18
I can't reproduce the described bug with the fix above; please let me know if it still triggers for you.
