### ISSUE TITLE
xinfo exception: Cannot convert value to long

### ISSUE THREAD

**Issue by CunningLogic** [pwndbg/pwndbg#888] opened 2021-02-23 20:00 UTC
### Description

xinfo throws a cannot convert value to long when used.

pwndbg> p m_array 
$1 = {{
    user_data = 0x0,
    request_size = 0
  }, {
    user_data = 0x0,
    request_size = 0
  }}
pwndbg> xinfo m_array 
Exception occurred: xinfo: Cannot convert value to long. (<class 'gdb.error'>)
For more info invoke `set exception-verbose on` and rerun the command
or debug it by yourself with `set exception-debugger on`
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> xinfo m_array 
Traceback (most recent call last):
  File "/home/jcase/storage/github/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/home/jcase/storage/github/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/jcase/storage/github/pwndbg/pwndbg/commands/xinfo.py", line 100, in xinfo
    addr = int(address)
gdb.error: Cannot convert value to long.

### Steps to reproduce

Use xinfo on anything.

### My setup
Ubuntu 20.04
Latest dev pwndbg as of today
GNU gdb (Ubuntu 9.2-0ubuntu1~20.04) 9.2
3.8.5 (default, Jul 28 2020, 12:59:40) 
[GCC 9.3.0]

**Comment by WeSeekAfterKnowledge** [comment] 2021-06-16 07:23
@CunningLogic can you upload a zipped copy of your target binary and the GDB script you're using?

**Comment by disconnect3d** [comment] 2021-06-18 11:14
I think it was reported previously and maybe that was the intended behavior?

To make it work, one has to pass `xinfo &<symbol>`

```
pwndbg> xinfo malloc
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/xinfo.py", line 100, in xinfo
    addr = int(address)
gdb.error: Cannot convert value to long.

pwndbg> xinfo &malloc
Extended information for virtual address 0x7ffff7dee690:

  Containing mapping:
    0x7ffff7dd3000     0x7ffff7dfc000 r-xp    29000 0      /lib/x86_64-linux-gnu/ld-2.27.so

  Offset information:
         Mapped Area 0x7ffff7dee690 = 0x7ffff7dd3000 + 0x1b690
         File (Base) 0x7ffff7dee690 = 0x7ffff7dd3000 + 0x1b690
      File (Segment) 0x7ffff7dee690 = 0x7ffff7dd3000 + 0x1b690
         File (Disk) 0x7ffff7dee690 = /lib/x86_64-linux-gnu/ld-2.27.so + 0x1b690

 Containing ELF sections:
               .text 0x7ffff7dee690 = 0x7ffff7dd3f10 + 0x1a780
```

**Comment by disconnect3d** [comment] 2021-06-18 11:17
```
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> set exception-debugger on
Set whether to debug exceptions raised in Pwndbg commands to True
pwndbg> xinfo malloc
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 130, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 221, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/xinfo.py", line 100, in xinfo
    addr = int(address)
gdb.error: Cannot convert value to long.

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
> /opt/pwndbg/pwndbg/commands/xinfo.py(100)xinfo()
     99 def xinfo(address=None):
--> 100     addr = int(address)
    101     addr &= pwndbg.arch.ptrmask

ipdb> print(address, type(address))
{void *(size_t)} 0x7ffff7dee690 <malloc> <class 'gdb.Value'>
ipdb> dir(address)
['__abs__', '__add__', '__and__', '__bool__', '__call__', '__class__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__float__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__gt__', '__hash__', '__index__', '__init__', '__init_subclass__', '__int__', '__invert__', '__le__', '__len__', '__lshift__', '__lt__', '__mod__', '__mul__', '__ne__', '__neg__', '__new__', '__or__', '__pos__', '__pow__', '__radd__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__rlshift__', '__rmod__', '__rmul__', '__ror__', '__rpow__', '__rrshift__', '__rshift__', '__rsub__', '__rtruediv__', '__rxor__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__truediv__', '__xor__', 'address', 'cast', 'const_value', 'dereference', 'dynamic_cast', 'dynamic_type', 'fetch_lazy', 'is_lazy', 'is_optimized_out', 'lazy_string', 'reference_value', 'referenced_value', 'reinterpret_cast', 'rvalue_reference_value', 'string', 'type']
ipdb> pwndbg.memory.pvoid(address)
5188183029801913160
ipdb> type(pwndbg.memory.pvoid(address))
<class 'int'>
```

Note that:
```
ipdb> pwndbg.memory.pvoid(address)
5188183029801913160
```
is wrong, the address is incorrect here.. hm.

**Comment by disconnect3d** [comment] 2021-06-18 11:29
Fixed in https://github.com/pwndbg/pwndbg/commit/668e53f5279cfb86b75d852061d3b32b44b69408

**Closed as completed by disconnect3d** 2021-06-18 11:29 UTC
Labels: bug
