### ISSUE TITLE
Maximum recursion depth exceeded with get_ehdr

### ISSUE THREAD

**Issue by j3s5e4** [pwndbg/pwndbg#1219] opened 2022-10-04 17:23 UTC
### Description

The `get_ehdr()` function gets stuck in a loop in some cases. In my instance, when connecting to gdbserver without the proc filesystem available.

```
Starting at
stack.py:78 update()
-> stack.py:127 is_executable()
-> elf.py:183 exe()
-> elf.py:221 load()
---> recursion starts here <---
-> elf.py:244 get_ehdr()
-> vmmap.py:113 find()  
-> vmmap.py:89 get()
-> vmmap.py:89,92,96 any of the calls to info_auxv(), info_sharedlibrary(), info_files()
-> elf.py: 338 map()
---> which is back to calling get_ehdr()
```

### Steps to reproduce

With a running gdbserver,
`target remote <ip>:<port>`

`Python exception <class 'RecursionError'>: maximum recursion depth exceeded in comparison`

### My setup

Gdb 12.0.90
Ubuntu 20.04
Pwndbg commit 3be45599707b29ede96db739e7debe1d4ab4ecc5 (latest as of Oct 4)

**Comment by disconnect3d** [comment] 2022-10-04 17:27
And that hits again :/. Fwiw this has been introduced with my changes to optimize some code paths, which I haven't tested on some edge case targets like this.

The main issue is that on those targets we don't have full vmmap information, so we try to obtain it using different tricks like parsing elf headers.

Previously, we were doing it by investigating known addresses and trying to find those memory areas by ... reading pages one by one. That was very inefficient for some targets, especially for bare metal ones.

Out of curiosuty, what target are u running this against @JesseAusten ?

**Comment by j3s5e4** [comment] 2022-10-04 17:29
I'm running this against a proprietary i386 binary on an x86_64 system.

**Comment by disconnect3d** [comment] 2022-10-04 17:30
Wait, why don't u have proc filesystem available then? :P

**Comment by j3s5e4** [comment] 2022-10-04 17:33
It works locally if I elevate permissions, but on my actual remote target it's a bit weird. But if pwndbg can't access /proc or whatever proc stuff is sent over gdbserver it just goes into that loop above.

**Comment by disconnect3d** [comment] 2022-10-04 17:34
Out of curiosity, does `info proc mappings` return anything? I think it also can't get pages info?

**Comment by disconnect3d** [comment] 2022-10-04 17:39
Fwiw, the commit that broke this is: https://github.com/pwndbg/pwndbg/commit/dc0e1f419a569963c76faa6125c2d5b53155255a

**Comment by disconnect3d** [comment] 2022-10-04 17:46
@JesseAusten reverting some of this commit and adjusting to recent changes in Pwndbg APIs would make this work likely.

I can't work on this right now, but maybe what we should do is:
- use vmmap if possible
- if it isn't present (well, info proc mappings isnt present?) then use the old way of traversing memory pages?

**Comment by j3s5e4** [comment] 2022-10-04 17:47
When it does the recursive exception I only get a process number. Fortunately for me it looks like I'm able to actually get the remote process to behave correctly and send over proc info, which makes this bug moot for me.

Also, I did notice that vmmap returned the libc mapping but no other entries.

**Comment by disconnect3d** [comment] 2022-10-04 17:48
Also if we know how to reproduce it properly, that would be useful for fixing this and having a test for this

**Comment by j3s5e4** [comment] 2022-10-04 17:50
I can reproduce it locally by running gdbserver in a chrooted environment which doesn't have access to /proc, and then connecting with gdb.

**Comment by disconnect3d** [comment] 2022-10-04 21:28
Ugh, I tried reproducing it with:
```
sudo docker run --privileged --rm -it --net host ubuntu bash
umount /proc
apt update && apt install -y gdbserver
gdbserver :1234 /bin/ls
```
And then `gdb -ex 'target remote :1234'` on host. However, the things are broken even on the pure GDB side when it is run with `--nx` to not load Pwndbg because GDBserver simply... do not detect the proper architecture of the target program. It reports i386 instead of x86-64 and so the gdb client can't even read registers properly.

**Comment by j3s5e4** [comment] 2022-10-04 21:29
I had similar issues until I updated both gdb and gdbserver. I believe I ended up using version 12.x

**Comment by disconnect3d** [comment] 2022-10-04 21:30
It is:
```
GNU gdbserver (Ubuntu 12.0.90-0ubuntu1) 12.0.90
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
```
for me

**Comment by disconnect3d** [comment] 2022-10-04 21:32
~~Weird. It works with gdb-multiarch O_o~~

EDIT: My mistake. I did not umount /proc in that run. It still does not work.

**Comment by disconnect3d** [comment] 2022-10-04 21:36
Same problem with `GNU gdbserver (Ubuntu 12.1-3ubuntu2) 12.1` but still on GDB 12.0.90. Will try with GDB 12.1.

**Comment by izeroo** [comment] 2023-02-20 07:01
Same problem here. I'm debugging a mips router remotely. It do have /proc filesystem
```
gdb-multiarch --version
GNU gdb (Ubuntu 8.1.1-0ubuntu1) 8.1.1

firmadyne/gdbserver --version
GNU gdbserver (GDB) 8.0
Copyright (C) 2017 Free Software Foundation, Inc.
gdbserver is free software, covered by the GNU General Public License.
This gdbserver was configured as "mips-linux-gnu"
```
```
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to 'on'.
pwndbg> c
Continuing.
Traceback (most recent call last):
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 732, in mark_pc_as_executable
    mapping = find(pwndbg.gdblib.regs.pc)
  File "/home/zeero/.local/pwndbg/pwndbg/lib/memoize.py", line 57, in __call__
    value = self.func(*args, **kwargs)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 151, in find
    for page in get():
  File "/home/zeero/.local/pwndbg/pwndbg/lib/memoize.py", line 57, in __call__
    value = self.func(*args, **kwargs)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 127, in get
    pages.extend(info_auxv())
  File "/home/zeero/.local/pwndbg/pwndbg/lib/memoize.py", line 57, in __call__
    value = self.func(*args, **kwargs)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 671, in info_auxv
    pages.extend(pwndbg.gdblib.elf.map(entry or phdr, exe_name))
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/elf.py", line 338, in map
    ei_class, ehdr = get_ehdr(pointer)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/elf.py", line 244, in get_ehdr
    vmmap = pwndbg.gdblib.vmmap.find(pointer)
  File "/home/zeero/.local/pwndbg/pwndbg/lib/memoize.py", line 57, in __call__
    value = self.func(*args, **kwargs)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 151, in find
    for page in get():
  File "/home/zeero/.local/pwndbg/pwndbg/lib/memoize.py", line 57, in __call__
    value = self.func(*args, **kwargs)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 127, in get
    pages.extend(info_auxv())
  File "/home/zeero/.local/pwndbg/pwndbg/lib/memoize.py", line 57, in __call__
    value = self.func(*args, **kwargs)
  File "/home/zeero/.local/pwndbg/pwndbg/gdblib/vmmap.py", line 671, in info_auxv
```

**Comment by disconnect3d** [comment] 2023-02-20 21:20
Hi, @izeroo can I ask you to check if this PR fixes it for you: https://github.com/pwndbg/pwndbg/pull/1585 ?

**Comment by disconnect3d** [comment] 2023-03-25 17:33
I am closing this as I can't reproduce this and there is no answer. I hope this is fixed already.

**Closed as completed by disconnect3d** 2023-03-25 17:33 UTC
Labels: bug
