### ISSUE TITLE
Incorrect Call Target

### ISSUE THREAD

**Issue by zachriggle** [pwndbg/pwndbg#112] opened 2016-09-23 02:19 UTC
Related to #107, single-stepping shows that the register-indirect call target is wrong.

```
 ► 0x4005d6 <__libc_csu_init+86>     mov    edi, r13d
   0x4005d9 <__libc_csu_init+89>     call   qword ptr [r12 + rbx*8]<0x30202b203231725b>
```

We can see what the target should be.

```
pwndbg> i r r12 rbx
r12            0x601000 0x601000
rbx            0x0      0x0
pwndbg> p *(void**)($r12 + $rbx*8)
$1 = (void *) 0x7fcc037fc6a0 <read>
```

```
 ► 0x4005d9 <__libc_csu_init+89>     call   qword ptr [r12 + rbx*8]       <0x7fcc037fc6a0>
        rdi: 0x0
        rsi: 0x601010 (sleep@got.plt) ◂— 0x7fcc037d1bc0 (sleep) —▸ push   r13
        rdx: 0x8
        rcx: 0x7fcc037fc6b0 (__read_nocancel+7) —▸ cmp    rax, -0xfff
```

Also note that we only see the address 0x7fcc037fc6a0, not the symbol <read> -- even when at that instruction.

We clearly have the data, it's just not showing up.

``` py
>>> i=pwndbg.disasm.one()
>>> hex(i.address)
'0x4005d9'
>>> hex(i.target)
'0x7fcc037fc6a0'
>>> i.symbol
'read@got.plt'
```

**Comment by zachriggle** [comment] 2016-09-23 03:04
```
>>> x=pwndbg.disasm.near(0x4005d6, 2, emulate=True)
# Instantiating Unicorn for x86-64
uc = U.Uc(4, 8)
Skipping blacklisted register 'cs'
Skipping blacklisted register 'ss'
Skipping blacklisted register 'ds'
Skipping blacklisted register 'es'
Skipping blacklisted register 'fs'
Skipping blacklisted register 'gs'
Skipping blacklisted register 'fsbase'
Skipping blacklisted register 'gsbase'
uc.reg_write(U.x86_const.UC_X86_REG_AX, 0x119)
uc.reg_write(U.x86_const.UC_X86_REG_AH, 0x1)
uc.reg_write(U.x86_const.UC_X86_REG_AL, 0x19)
uc.reg_write(U.x86_const.UC_X86_REG_CX, 0x26b0)
uc.reg_write(U.x86_const.UC_X86_REG_CH, 0x26)
uc.reg_write(U.x86_const.UC_X86_REG_CL, 0xffffffffffffffb0)
uc.reg_write(U.x86_const.UC_X86_REG_DX, 0x8)
uc.reg_write(U.x86_const.UC_X86_REG_DL, 0x8)
uc.reg_write(U.x86_const.UC_X86_REG_SIL, 0x10)
uc.reg_write(U.x86_const.UC_X86_REG_SPL, 0x60)
uc.reg_write(U.x86_const.UC_X86_REG_BPL, 0x1)
uc.reg_write(U.x86_const.UC_X86_REG_SI, 0x1010)
uc.reg_write(U.x86_const.UC_X86_REG_BP, 0x1)
uc.reg_write(U.x86_const.UC_X86_REG_SP, 0x7fffbed19560)
Skipping blacklisted register 'ip'
uc.reg_write(U.x86_const.UC_X86_REG_RAX, 0x119)
uc.reg_write(U.x86_const.UC_X86_REG_RCX, 0x7fd07ab026b0)
uc.reg_write(U.x86_const.UC_X86_REG_RDX, 0x8)
uc.reg_write(U.x86_const.UC_X86_REG_RSI, 0x601010)
uc.reg_write(U.x86_const.UC_X86_REG_R8, 0x7fffbed19430)
uc.reg_write(U.x86_const.UC_X86_REG_R9, 0x7fffbed19270)
uc.reg_write(U.x86_const.UC_X86_REG_R10, 0x7fffbed192c0)
uc.reg_write(U.x86_const.UC_X86_REG_R11, 0x246)
uc.reg_write(U.x86_const.UC_X86_REG_R12, 0x601000)
uc.reg_write(U.x86_const.UC_X86_REG_R14, 0x601010)
uc.reg_write(U.x86_const.UC_X86_REG_R15, 0x8)
uc.reg_write(U.x86_const.UC_X86_REG_RBP, 0x1)
uc.reg_write(U.x86_const.UC_X86_REG_RSP, 0x7fffbed19560)
uc.reg_write(U.x86_const.UC_X86_REG_RIP, 0x4005d6)
uc.reg_write(U.x86_const.UC_X86_REG_EFLAGS, 0x202)
uc.reg_write(U.x86_const.UC_X86_REG_EFLAGS, 0x202)
70865104 = uc.hook_add(*(112, <bound method Emulator.hook_mem_invalid of <pwndbg.emu.emulator.Emulator object at 0x7f847641b550>>), **{})
70870112 = uc.hook_add(*(1, <bound method Emulator.hook_intr of <pwndbg.emu.emulator.Emulator object at 0x7f847641b550>>), **{})
# Mapping 0x400000-0x401000
uc.mem_map(0x400000, 0x1000)
# Writing 0x1000 bytes
uc.mem_write(0x400000, ...)
69943520 = uc.hook_add(*(4, <bound method Emulator.trace_hook of <pwndbg.emu.emulator.Emulator object at 0x7f847641b550>>), **{})
# Single-stepping at 0x4005d6: mov edi, r13d
69944176 = uc.hook_add(*(4, <bound method Emulator.single_step_hook_code of <pwndbg.emu.emulator.Emulator object at 0x7f847641b550>>), **{})
uc.emu_start(*(4195798, 0), **{'count': 1})
uc.mem_read(*(4195798, 3), **{})
# trace_hook: 0x4005d6 b'4489ef'
# single_step: 0x4005d6
uc.mem_read(*(4195801, 4), **{})
# trace_hook: 0x4005d9 b'41ff14dc'
# single_step: 0x4005d9
uc.hook_del(*(69944176,), **{})
# Single-stepping at 0x4005d9: call qword ptr [r12 + rbx*8]
70864160 = uc.hook_add(*(4, <bound method Emulator.single_step_hook_code of <pwndbg.emu.emulator.Emulator object at 0x7f847641b550>>), **{})
uc.emu_start(*(4195801, 0), **{'count': 1})
uc.mem_read(*(4195801, 4), **{})
# trace_hook: 0x4005d9 b'41ff14dc'
# single_step: 0x4005d9
# Invalid access at 0x601000
# Mapping 0x601000-0x602000
uc.mem_map(0x601000, 0x1000)
# Writing 0x1000 bytes
uc.mem_write(0x601000, ...)
# Invalid access at 0x7fffbed19558
# Mapping 0x7fffbed19000-0x7fffbed1a000
uc.mem_map(0x7fffbed19000, 0x1000)
# Writing 0x1000 bytes
uc.mem_write(0x7fffbed19000, ...)
# Invalid access at 0x7fd07ab026a0
# Mapping 0x7fd07ab02000-0x7fd07ab03000
uc.mem_map(0x7fd07ab02000, 0x1000)
# Writing 0x1000 bytes
uc.mem_write(0x7fd07ab02000, ...)
uc.mem_read(*(140533388289696, 7), **{})
# trace_hook: 0x7fd07ab026a0 b'833dcd892d0000'
uc.hook_del(*(70864160,), **{})
```

It looks like the emulator is correct?  It's definitely stepping to `0x7fd07ab026a0`, which is `read`.

```
pwndbg> info symbol 0x7fd07ab026a0
read in section .text of /lib/x86_64-linux-gnu/libc.so.6
```

**Comment by disconnect3d** [comment] 2017-04-18 10:05
At my machine I can test this using `gdb -q /bin/bash` and then `b __libc_csu_init` - then single stepping to this call.

This instruction is adding the target to the string and so `ins.target` is faulty in this function:
https://github.com/pwndbg/pwndbg/blob/master/pwndbg/color/disasm.py#L62

I am not yet sure where is this function called.

**Comment by disconnect3d** [comment] 2017-04-18 10:52
The problem comes from `one`, then `get_one_instruction`:
![image](https://cloud.githubusercontent.com/assets/10009354/25126922/350cfc62-2434-11e7-85d2-9ec4deb45672.png)
Then it is caused by `pwndbg.disasm.arch.DisassemblyAssistant.enhance(ins)` and there by `enhancer.enhance_next(instruction)`.

In the end I end up at https://github.com/pwndbg/pwndbg/blob/master/pwndbg/disasm/arch.py#L123-L155 which returns bad address.

**Comment by disconnect3d** [comment] 2017-04-18 19:25
Can also be tested on such case:
```C
#include <stdio.h>
#include <math.h>

int main(int argc, char* argv[]) {
    double (*fp[])(double) = {sin, cos};

    double x = fp[argc-1](2.3);

    printf("%lf\n", x);
}
```

Compiled as `gcc main.c -lm -O2` (note: the -O1/2/3 is crucial as -O0 does `call rax` - at least on my setup).

**Comment by disconnect3d** [comment] 2017-04-18 19:57
I am not sure how to fix `memory_sz` but the problem probably comes from [`enhance_operands`](https://github.com/pwndbg/pwndbg/blob/master/pwndbg/disasm/arch.py#L178-L205). I have added such print at the begining and end of `enhance_operands`:
```python
        print('>>>>>>>>>>>>> Enhancing operands for ', instruction.mnemonic, hex(instruction.address))

        for i, op in enumerate(instruction.operands):
            op.int    = None
            op.symbol = None

            op.int = self.op_handlers.get(op.type, lambda *a: None)(instruction, op)
            if op.int:
                op.int &= pwndbg.arch.ptrmask
            op.str = self.op_names.get(op.type, lambda *a: None)(instruction, op)

            if op.int:
                op.symbol = pwndbg.symbol.get(op.int)

        for o in instruction.operands:
            print(o.__dict__)
```

For the wrong call:
```
   0x4004e3 <main+35>    call   qword ptr [rsp + rdi*8]<0x31202b207073725b>
```
It printed:
```
>>>>>>>>>>>>> Enhancing operands for  call 0x4004e3
{'int': None, 'symbol': None, 'str': '[rsp + 1*0x8]'}
```

**Comment by disconnect3d** [comment] 2017-04-18 20:38
@zachriggle Can you look over it and/or help?

Here is a workaround for my case which partially works...:
https://github.com/disconnect3d/pwndbg/commit/f0de544bea3bf57d5c7d094f53c96e974d9537b4

And a recording:
https://asciinema.org/a/3mhbcq2too6ey8kkyul1gif4b

Shouldn't we emulate this up to the call and have proper target and display it?

**Comment by disconnect3d** [comment] 2024-04-28 12:37
This has been fixed with the recent disassembly and emulation enhancements.

**Closed by disconnect3d** 2024-04-28 12:37 UTC
Labels: bug, help wanted, emulation
