### ISSUE TITLE
Stepping over system()/popen() causes termination and changes gdb target to "command"

### ISSUE THREAD

**Issue by dan1338** [pwndbg/pwndbg#950] opened 2021-08-20 09:33 UTC
### Description

It seems like the system()/popen() libc funcions are not handled correctly.
When trying to 'stepover' or 'stepret' over them the program terminates and gdb target changes to the first argument of aforementioned function.

ldso error when doing 'stepover' system@plt("/bin/ls")
```
sh: /usr/lib/libc.so.6: version `GLIBC_2.3' not found (required by sh)
```

In the case of 'stepret' /bin/ls is executed but the program terminates and we lose control over execution,
contrary to normal gdb where 'finish' goes over system() and restores control on ret instruction

### Steps to reproduce
```c
// gcc test.c -o test ; gdb ./test
int main(void) { system("/bin/ls"); }
```
```gdb
b main
r
# ► 0x555555555139 <main+4>               lea    rdi, [rip + 0xec4]
#   0x555555555140 <main+11>              mov    eax, 0
#   0x555555555145 <main+16>              call   system@plt                <system@plt>
#   0x55555555514a <main+21>              mov    eax, 0
#   0x55555555514f <main+26>              pop    rbp
#   0x555555555150 <main+27>              ret
so *main+16
info target
# Symbols from "/usr/bin/dash".
# Local exec file:
#   `/usr/bin/dash', file type elf64-x86-64.
```

### My setup
Gdb:      10.2
Python:   3.9.6 (default, Jul  6 2021, 18:29:50)  [GCC 10.2.1 20201203]
Pwndbg:   1.1.0 build: b9e7bf1
Capstone: 4.0.1024
Unicorn:  1.0.3

**Comment by disconnect3d** [comment] 2021-08-21 22:25
Hey, this is not a bug. We do set `follow-fork-mode` GDB setting/parameter to `child` in `pwndbg/__init__.py`, so that when the process forks, we change the debugged process to the children.

You can see this setting's value via:
```
pwndbg> show follow-fork-mode 
Debugger response to a program call of fork or vfork is "child".
```

And you can change it to follow the parent instead via: `set follow-fork-mode parent`. This way, doing the step over the `system` and similar functions will work as you expect it to work.

Hope this helps :).

Closing this for now; please reply/reopen or create a new issue if this doesn't work for you or/and you find any other issues here :).

**Closed as completed by disconnect3d** 2021-08-21 22:25 UTC
Labels: invalid

**Comment by dan1338** [comment] 2021-08-22 09:49
Oh right, didn't know about that. Maybe it would have been wiser to have a default setting that's the same as normal gdb to reduce confusion?

**Comment by disconnect3d** [comment] 2021-08-22 10:59
@1338-1 Hmm, good question; I am not sure why we did this in the first place, so I will ran this idea over on our Discord.
