### ISSUE TITLE
Heap heuristics may crash if libc.so is dynamically linked but no symbols are present for it

### ISSUE THREAD

**Issue by disconnect3d** [pwndbg/pwndbg#1231] opened 2022-10-06 01:37 UTC
This is weird:
```
dc@jhtc:~$ gdb --quiet -ex 'set context-sections ""' -ex 'set auto-solib-add off' -ex 'set resolve-heap-via-heuristic on' -ex 'entry' /bin/ls
pwndbg: loaded 207 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from /bin/ls...
(No debugging symbols found in /bin/ls)
Sections set to be empty. FYI valid values are: regs, disasm, args, code, stack, backtrace, expressions, ghidra
You are going to resolve the heap via heuristic. This might not work in all cases.
You are going to resolve the heap via heuristic. This might not work in all cases.
Temporary breakpoint 1 at 0x555555559850
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Temporary breakpoint 1, 0x0000555555559850 in ?? ()
------- tip of the day (disable with set show-tips off) -------
Pwndbg context displays where the program branches to thanks to emulating few instructions into the future. You can disable this with set emulate off which may also speed up debugging
You are going to resolve the heap via heuristic. This might not work in all cases.
pwndbg> set exception-verbose on
Set whether to print a full stacktrace for exceptions raised in Pwndbg commands to True
pwndbg> heap
Traceback (most recent call last):
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 147, in __call__
    return self.function(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 218, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 273, in _OnlyWithResolvedHeapSyms
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/__init__.py", line 243, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/opt/pwndbg/pwndbg/commands/heap.py", line 126, in heap
    heap_region = allocator.get_heap_boundaries(addr)
  File "/opt/pwndbg/pwndbg/heap/ptmalloc.py", line 1717, in get_heap_boundaries
    arena = self.get_arena(addr)
  File "/opt/pwndbg/pwndbg/heap/ptmalloc.py", line 1703, in get_arena
    return self.main_arena
  File "/opt/pwndbg/pwndbg/heap/ptmalloc.py", line 885, in main_arena
    elif self.is_glibc_static_symbol(main_arena_via_symbol):
  File "/opt/pwndbg/pwndbg/heap/ptmalloc.py", line 872, in is_glibc_static_symbol
    _IO_list_all_addr = pwndbg.symbol.address("_IO_list_all")
  File "/opt/pwndbg/pwndbg/lib/memoize.py", line 51, in __call__
    value = self.func(*args, **kwargs)
  File "/opt/pwndbg/pwndbg/symbol.py", line 215, in address
    address = int(re.search("0x[0-9a-fA-F]+", result).group(), 0)
AttributeError: 'NoneType' object has no attribute 'group'

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
pwndbg>
```

**Comment by lebr0nli** [comment] 2022-10-06 03:28
Yeah, I think this is probably because we are missing `_IO_list_all` for this `/bin/ls`, which is important for the heuristic to find which page the symbols locate in.
Btw for my `/bin/ls`, it works:

```text
$ gdb --quiet -ex 'set context-sections ""' -ex 'set auto-solib-add off' -ex 'set resolve-heap-via-heuristic on' -ex 'entry' /bin/ls
pwndbg: loaded 196 commands. Type pwndbg [filter] for a list.
pwndbg: created $rebase, $ida gdb functions (can be used with print/break)
Reading symbols from /bin/ls...
(No debugging symbols found in /bin/ls)
Sections set to be empty. FYI valid values are: regs, disasm, args, code, stack, backtrace, expressions, ghidra
No symbol table is loaded.  Use the "file" command.
warning: Error disabling address space randomization: Operation not permitted
Temporary breakpoint 1 at 0x55686b0b77d0
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".

Temporary breakpoint 1, 0x000055686b0b77d0 in ?? ()
GEP is running now!
pwndbg> heap
Allocated chunk | PREV_INUSE
Addr: 0x55686b81b000
Size: 0x291

Free chunk (tcache) | PREV_INUSE
Addr: 0x55686b81b290
Size: 0x1e1
fd: 0x00

Free chunk (tcache) | PREV_INUSE
Addr: 0x55686b81b470
Size: 0x81
fd: 0x00

Free chunk (tcache) | PREV_INUSE
Addr: 0x55686b81b4f0
Size: 0x411
fd: 0x00

Top chunk | PREV_INUSE
Addr: 0x55686b81b900
Size: 0x20701
```

I think the implementation of the heuristic to find the symbols need to be improved because it's still too easy to fail...
I'll try to find some new solutions to enhance it in my free time.

Btw, could I get this libc or environment for testing?

**Comment by disconnect3d** [comment] 2022-10-06 03:31
This is on Ubuntu 18.04.6 and indeed that's on the symbol you mentioned:
```
> /opt/pwndbg/pwndbg/symbol.py(215)address()
    214         result = gdb.execute("info address %s" % symbol, to_string=True, from_tty=False)
--> 215         address = int(re.search("0x[0-9a-fA-F]+", result).group(), 0)
    216

ipdb> print(result)
Symbol "_IO_list_all" is unresolved.

ipdb> print(symbol)
_IO_list_all
```

Interestingly, my friend who initially send me this bug, sent me this traceback, which says he is missing other symbol:
```
pwndbg> heap
Traceback (most recent call last):
  File "/home/lukasz/c/pwndbg/pwndbg/commands/__init__.py", line 147, in __call__
    return self.function(*args, **kwargs)
  File "/home/lukasz/c/pwndbg/pwndbg/commands/__init__.py", line 218, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/lukasz/c/pwndbg/pwndbg/commands/__init__.py", line 273, in _OnlyWithResolvedHeapSyms
    return function(*a, **kw)
  File "/home/lukasz/c/pwndbg/pwndbg/commands/__init__.py", line 243, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/home/lukasz/c/pwndbg/pwndbg/commands/heap.py", line 127, in heap
    heap_region = allocator.get_heap_boundaries(addr)
  File "/home/lukasz/c/pwndbg/pwndbg/heap/ptmalloc.py", line 1755, in get_heap_boundaries
    arena = self.get_arena(addr)
  File "/home/lukasz/c/pwndbg/pwndbg/heap/ptmalloc.py", line 1741, in get_arena
    return self.main_arena
  File "/home/lukasz/c/pwndbg/pwndbg/heap/ptmalloc.py", line 928, in main_arena
    malloc_hook_addr = pwndbg.symbol.address("__malloc_hook")
  File "/home/lukasz/c/pwndbg/pwndbg/lib/memoize.py", line 51, in __call__
    value = self.func(*args, **kwargs)
  File "/home/lukasz/c/pwndbg/pwndbg/symbol.py", line 215, in address
    address = int(re.search("0x[0-9a-fA-F]+", result).group(), 0)
AttributeError: 'NoneType' object has no attribute 'group'

> /home/lukasz/c/pwndbg/pwndbg/symbol.py(215)address()
-> address = int(re.search("0x[0-9a-fA-F]+", result).group(), 0)
(Pdb) print(result)
Symbol "__malloc_hook" is unresolved.
```
But he was using Ubuntu on Windows + WSL (2 I think)

**Comment by disconnect3d** [comment] 2022-10-06 03:32
@lebr0nli Anyway, we need a better error handling on those cases. We need to display to tell the user sth like "hey we can't find this symbol with our heuristics; you need to provide its address to us if you can determine it, here's how:"

**Comment by lebr0nli** [comment] 2022-10-06 04:45
> Interestingly, my friend who initially send me this bug, sent me this traceback, which says he is missing other symbol:

For this, I think I'll fix this by checking `__malloc_chunk` exist or not before we using GEF's magic for `main_arena`.
(But a little weird thing is that these `AttributeError` seems to occur in `pwndbg.symbol.address` instead of some heap functions, I'll check it later to see what's going on.)

> Anyway, we need a better error handling on those cases. We need to display to tell the user sth like "hey we can't find this symbol with our heuristics; you need to provide its address to us if you can determine it, here's how:"

Ok, I'll add some checks and hints for this!

**Comment by disconnect3d** [comment] 2022-10-06 04:46
Btw it goes the same with glibc check. The user should not see some kind of bogus ">=" comparison error when they do not set glibc version, but an info they need to set it 😅

**Comment by lebr0nli** [comment] 2022-10-06 07:26
> Btw it goes the same with glibc check. The user should not see some kind of bogus ">=" comparison error when they do not set glibc version, but an info they need to set it 😅

Ok, I'll fix that, too.

**Comment by disconnect3d** [comment] 2022-10-11 07:55
Is this all fixed with #1242?

**Comment by lebr0nli** [comment] 2022-10-11 08:34
> Is this all fixed with #1242?

For all the bad error-handling parts you mentioned, yes, it should be fixed with #1242 now.

But for the main issue about this libc, hmm, I'm not sure, because I didn't find a way to reproduce the environments in the end.
Is the libc of your friend have `__libc_free`, `__libc_malloc`, `__libc_calloc`, and `malloc_trim` although it doesn't have `_IO_list_all` and `__malloc_hook`?
Since we don't always need `_IO_list_all` now, if the libc has the above functions' symbol and pwndbg can find libc's `.got.plt`, it should probably work.
~~(But if this libc really has no symbols, it won't work and I have no ideas about how to fix it currently😥 )~~
Edit: After some recent updates about heap heuristics, we have ability to run the `heap` command without any libc symbols now.

**Comment by itewqq** [comment] 2023-02-28 16:09
Same error here.

```
pwndbg> bins
bins: Fail to resolve the symbol: `main_arena`
You can try to determine the libc symbols addresses manually and set them appropriately. For this, see the `heap_config` command output and set the config for `main_arena`.
Traceback (most recent call last):
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 320, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 406, in _OnlyWithResolvedHeapSyms
    return _try2run_heap_command(function, a, kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 376, in _try2run_heap_command
    raise err
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 363, in _try2run_heap_command
    return function(*a, **kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 345, in _OnlyWhenHeapIsInitialized
    return function(*a, **kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/heap.py", line 413, in bins
    if tcache_addr is None and pwndbg.heap.current.thread_cache is None:
  File "/home/itemqq/Pwn/pwndbg/pwndbg/heap/ptmalloc.py", line 1522, in thread_cache
    arena = self.thread_arena
  File "/home/itemqq/Pwn/pwndbg/pwndbg/heap/ptmalloc.py", line 1453, in thread_arena
    if self.main_arena.address != pwndbg.heap.current.main_arena.next or self.multithreaded:
  File "/home/itemqq/Pwn/pwndbg/pwndbg/heap/ptmalloc.py", line 1328, in main_arena
    raise SymbolUnresolvableError("main_arena")
pwndbg.heap.ptmalloc.SymbolUnresolvableError: `main_arena` can not be resolved via heuristic

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
```
```sh
$ file libc-2.36.so
libc-2.36.so: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d1704d25fbbb72fa95d517b883131828c0883fe9, for GNU/Linux 3.2.0, stripped
```

**Comment by lebr0nli** [comment] 2023-02-28 17:24
@itewqq 
Hi, the heap heuristic on the latest commit work fine for me here using the same libc:
```
pwndbg> ctx code
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
──────────────────────────────────────────────────[ SOURCE (CODE) ]───────────────────────────────────────────────────
In file: /tmp/heap/test.c
   3 int main(){
   4     void *a[15];
   5     for(int i = 0; i < 15; ++i) a[i] = malloc(0x10);
   6     for(int i = 0; i < 15; ++i) free(a[i]);
   7     return 0;
 ► 8 }
pwndbg> info sharedlibrary
From                To                  Syms Read   Shared Object Library
0x00007f456c2c70a0  0x00007f456c2ef465  Yes (*)     ./ld-linux-x86-64.so.2
0x00007f456c0e1700  0x00007f456c25847d  Yes (*)     ./libc.so.6
pwndbg> !file ./libc.so.6
./libc.so.6: ELF 64-bit LSB shared object, x86-64, version 1 (GNU/Linux), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=d1704d25fbbb72fa95d517b883131828c0883fe9, for GNU/Linux 3.2.0, stripped
pwndbg> p &main_arena
No symbol "main_arena" in current context.
pwndbg> p &mp_
No symbol "mp_" in current context.
pwndbg> bins
tcachebins
0x20 [  7]: 0x55f56db47360 —▸ 0x55f56db47340 —▸ 0x55f56db47320 —▸ 0x55f56db47300 —▸ 0x55f56db472e0 —▸ 0x55f56db472c0 —▸ 0x55f56db472a0 ◂— 0x0
fastbins
0x20: 0x55f56db47450 —▸ 0x55f56db47430 —▸ 0x55f56db47410 —▸ 0x55f56db473f0 —▸ 0x55f56db473d0 ◂— ...
0x30: 0x0
0x40: 0x0
0x50: 0x0
0x60: 0x0
0x70: 0x0
0x80: 0x0
unsortedbin
all: 0x0
smallbins
empty
largebins
empty
```

Can you provide more information about the binary you debug on and the steps to reproduce it?
And maybe the output of `info sharedlibrary` and `info files` pls? (since I have a sneaking suspicion that we can't determine it because we failed to find libc by parsing these outputs or something)

Btw, the debug symbols for your libc seems can be found here: http://archive.ubuntu.com/ubuntu/pool/main/g/glibc/libc6-dbg_2.36-0ubuntu4_amd64.deb , maybe you can use the debug symbols here as the temporary workaround.

**Comment by itewqq** [comment] 2023-03-01 17:59
@lebr0nli Thanks for the hints. The pwndbg work fine for my original libc of the OS.
The error arises when I try to use pwntools to load the libc so to run a binary:

```python
#!/bin/python3

from pwn import *

context.log_level = 'debug'
elf = "./helloworld"
libc = ELF("./libc-2.36.so")

context(arch = 'amd64' , os = 'linux')

sh = process([elf], env={"LD_PRELOAD":"./libc-2.36.so"})
```

```sh
$ gdb -q -p $(pgrep babyheap)
...
pwndbg> heap
heap: Fail to resolve the symbol: `main_arena`
You can try to determine the libc symbols addresses manually and set them appropriately. For this, see the `heap_config` command output and set the config for `main_arena`.
Traceback (most recent call last):
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 184, in __call__
    return self.function(*args, **kwargs)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 320, in _OnlyWhenRunning
    return function(*a, **kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 406, in _OnlyWithResolvedHeapSyms
    return _try2run_heap_command(function, a, kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 376, in _try2run_heap_command
    raise err
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 363, in _try2run_heap_command
    return function(*a, **kw)
  File "/home/itemqq/Pwn/pwndbg/pwndbg/commands/__init__.py", line 344, in _OnlyWhenHeapIsInitialized
    if pwndbg.heap.current.is_initialized():
  File "/home/itemqq/Pwn/pwndbg/pwndbg/heap/ptmalloc.py", line 1732, in is_initialized
    self.can_be_resolved() and self.main_arena.top != 0
  File "/home/itemqq/Pwn/pwndbg/pwndbg/heap/ptmalloc.py", line 1328, in main_arena
    raise SymbolUnresolvableError("main_arena")
pwndbg.heap.ptmalloc.SymbolUnresolvableError: `main_arena` can not be resolved via heuristic

If that is an issue, you can report it on https://github.com/pwndbg/pwndbg/issues
(Please don't forget to search if it hasn't been reported before)
To generate the report and open a browser, you may run `bugreport --run-browser`
PS: Pull requests are welcome
> /home/itemqq/Pwn/pwndbg/pwndbg/heap/ptmalloc.py(1328)main_arena()
-> raise SymbolUnresolvableError("main_arena")
```

**Comment by CptGibbon** [comment] 2023-03-01 22:30
Does the dynamic linker match the GLIBC version?

**Comment by lebr0nli** [comment] 2023-03-02 07:48
@itewqq 
Thanks for the script to reproduce the bug!
Since the libc is loaded with `LD_PRELOAD=./libc-2.36.so`, the filename of libc will become `./libc-2.36.so` instead of `/path/to/libc.so.6`, so we failed to parse the output of `info sharedlibrary` to find the libc.
I forgot about this possibility, I’ll try to fix it.

Btw, you can rename your `libc-2.xx.so` to `libc.so.6` if you need to use the heap heuristic with `LD_PRELOAD` for now.

**Comment by itewqq** [comment] 2023-03-02 08:53
@lebr0nli Cool, happy to see it's working now, thanks!

**Comment by gsingh93** [comment] 2023-03-19 18:26
@lebr0nli can this be closed?

**Comment by lebr0nli** [comment] 2023-03-19 23:45
> can this be closed?

Yes, I think we can close this.
For the main cause of this issue, we won't encounter that again.
Even if the heap heuristic somehow crashes on stripped libc.so in the future, we should probably open another separate issue for that case.

**Closed as completed** 2023-03-19 23:45 UTC
Labels: bug, heap
