### ISSUE TITLE
telescope trouble

### ISSUE THREAD

**Issue by mrFOXYmr** [pwndbg/pwndbg#927] opened 2021-06-08 13:33 UTC
I tried to see what is on the stack in pwndbg via telescope. pwndbg gives me an instruction that matched the asm instruction, but in fact there is a string line. peda-gdb has no such problem. below screenshots. mb in pwndbg some settings for that?
![peda](https://user-images.githubusercontent.com/82227821/121193668-3bdf3480-c898-11eb-856a-db0dd63c132d.jpeg)
![pwndbg](https://user-images.githubusercontent.com/82227821/121193679-3da8f800-c898-11eb-9697-0c66b24a4aad.jpeg)

**Comment by WeSeekAfterKnowledge** [comment] 2021-06-16 07:16
This looks like a permission issue in `pwndbg.vmmap`.

**Comment by WeSeekAfterKnowledge** [comment] 2021-06-16 07:17
Can you upload your pwnable / binary and a script to get it into this state>. It looks like Pwndbg thinks 8048910 is only read-write, but is not executable.

**Comment by disconnect3d** [comment] 2021-06-18 11:31
@WeSeekAfterKnowledge actually, it seems the opposite?

I guess the 0x8048910 has read+execute mode and we may prioritize the display of code faster than strings?

(A string address can be R+X e.g. with PIE/PIC binaries when rip-relative-addressing is used)

**Comment by disconnect3d** [comment] 2021-06-18 11:32
Btw interestingly, a string was displayed for the 0x80481ec address along with the asm code. Why wasn't it the case for 0x8048910? Do we have a heuristic that expects string to be `[A-Za-z0-9]+` or something?

**Comment by mrFOXYmr** [comment] 2021-06-18 14:57
http://challenge01.root-me.org/cracking/ch4/ch4.zip <— this is that binary

**Comment by disconnect3d** [comment] 2021-08-21 22:37
Tried to reproduce this with:
```c
#include <stdio.h>
#include <string.h>
#include <sys/mman.h>

int main(void) {
    char* m = (char*)mmap(0, 128, PROT_READ|PROT_WRITE|PROT_EXEC, MAP_PRIVATE|MAP_ANONYMOUS, 0, 0);
    strcpy(m, "this is some text");
    printf("Some text = '%s'\n", m);
}
```

Even though the string is in RWX memory, we display both its instruction and string:
```
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
───────────────────────────────────────────────────────────────────[ REGISTERS ]───────────────────────────────────────────────────────────────────
*RAX  0x0
 RBX  0x5555555551f0 (__libc_csu_init) ◂— endbr64 
*RCX  0x78657420656d6f73 ('some tex')
*RDX  0x2073692073696874 ('this is ')
*RDI  0x555555556004 ◂— "Some text = '%s'\n"
*RSI  0x7ffff7fc2000 ◂— je     0x7ffff7fc206a /* 0x2073692073696874; 'this is some text' */
 R8   0x0
 R9   0x0
*R10  0x22
*R11  0x246
 R12  0x555555555080 (_start) ◂— endbr64 
 R13  0x0
 R14  0x0
 R15  0x0
 RBP  0x7fffffffdde0 ◂— 0x0
 RSP  0x7fffffffddd0 —▸ 0x7fffffffded0 ◂— 0x1
*RIP  0x5555555551d6 (main+109) ◂— call   0x555555555070
────────────────────────────────────────────────────────────────────[ DISASM ]─────────────────────────────────────────────────────────────────────
   0x5555555551bd <main+84>     mov    word ptr [rax + 0x10], 0x74
   0x5555555551c3 <main+90>     mov    rax, qword ptr [rbp - 8]
   0x5555555551c7 <main+94>     mov    rsi, rax
   0x5555555551ca <main+97>     lea    rdi, [rip + 0xe33]
   0x5555555551d1 <main+104>    mov    eax, 0
 ► 0x5555555551d6 <main+109>    call   printf@plt                <printf@plt>
        format: 0x555555556004 ◂— "Some text = '%s'\n"
        vararg: 0x7ffff7fc2000 ◂— je     0x7ffff7fc206a /* 0x2073692073696874; 'this is some text' */
```

Works also for the weird formatted text too:
```
*RSI  0x7ffff7fc2000 ◂— pop    rdi /* 0x6d35336a4763305f; '_0cGj35mVasdsadsadsadasdasd' */
```

```
──────────────────────────────────────────[ STACK ]──────────────────────────────────────────
00:0000│ rsp 0x7fffffffddd0 —▸ 0x7fffffffded0 ◂— 0x1
01:0008│     0x7fffffffddd8 —▸ 0x7ffff7fc2000 ◂— pop    rdi /* 0x6d35336a4763305f; '_0cGj35mVasdsadsadsadasdasd' */
```

Also works fine if we `mprotect` the memory to `PROT_READ|PROT_EXEC`.

**Comment by disconnect3d** [comment] 2021-08-21 22:48
I am closing this issue as I can't reproduce it. I also can't download the binary as it requires auth.

@mrFOXYmr if you send me the binary via e-mail (dominik.b.czarnota+pwndbg <at> gmail.com) I can check it out. Otherwise,  I can't help.

**Closed as completed by disconnect3d** 2021-08-21 22:48 UTC
Labels: feature
