### ISSUE TITLE
When "continue" in breakpoint commands, error is occurred

### ISSUE THREAD

**Issue by Uniguri** [pwndbg/pwndbg#1653] opened 2023-03-29 13:31 UTC
### Description

In any binary, If "continue" command in breakpoint commands, pwndbg occur error.

```
~$ cat ./a.c
#include <stdio.h>
int main()
{
        printf("aa");
        return 0;
}
```
And "gcc ./a.c" then "gdb ./a.out" work like this (useless information is omitted)
```
pwndbg> set exception-debugger on
pwndbg> set exception-verbose on
pwndbg> b  *main
pwndbg> commands
>continue
>end
pwndbg> r
Starting program: /home/(this_is_secret)/a.out

Breakpoint 1, 0x0000555555555149 in main ()
Traceback (most recent call last):
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/hooks.py", line 32, in update_arch
    arch_mod.update()
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/arch.py", line 57, in update
    arch_name, ptrsize, endian = _get_arch(typeinfo.ptrsize)
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/arch.py", line 37, in _get_arch
    arch = gdb.newest_frame().architecture().name()
gdb.error: Selected thread is running.

> /home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/arch.py(37)_get_arch()
-> arch = gdb.newest_frame().architecture().name()

[1]+  Stopped                 gdb ./a.out
```

### Steps to reproduce

1. make breakpoint at any address.
2. make breakpoint commands containing "continue" for it.
3. run the program.
4. pwnbdg occur error

### My setup
```
pwndbg> version
Gdb:      13.1
Python:   3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Pwndbg:   2023.03.19 build: 3c9d09b
Capstone: 4.0.1024
Unicorn:  2.0.1

Distributor ID: Ubuntu
Description:    Ubuntu 20.04.5 LTS
Release:        20.04
Codename:       focal
```
And my ubuntu is installed on WSL2.

**Comment by gsingh93** [comment] 2023-03-29 14:48
Does this work for you without pwndbg? This is likely an issue with GDB itself, see https://github.com/pwndbg/pwndbg/issues/425.

**Comment by disconnect3d** [comment] 2023-03-29 15:47
Alternatively: can you also test this with `set memoize off` beforehand?

**Comment by Uniguri** [comment] 2023-03-30 01:42
When disable pwndbg and do it with vanila gdb, It does not occur error.
```
(gdb) b *main
Breakpoint 1 at 0x1149
(gdb) commands
>continue
>end
(gdb) r

Breakpoint 1, 0x0000555555555149 in main ()
aa[Inferior 1 (process 184) exited normally]
```

I typed "set memoize off" but, pwndbg says like
```
pwndbg> set memoize off
No symbol table is loaded.  Use the "file" command.
```

**Comment by disconnect3d** [comment] 2023-03-31 12:26
Sorry, I believe `memoize` is just a command, so please try just `memoize off`. Maybe that should be a config var instead, ugh.

**Comment by Uniguri** [comment] 2023-04-01 14:40
I typed "memoize", then Caching is off.
But, same error is occurred.
```
pwndbg> set exception-verbose on
pwndbg> set exception-debugger on
pwndbg> memoize
Caching is now OFF (pwndbg will work slower, use only for debugging pwndbg)
pwndbg> b *main
pwndbg> commands
>continue
>end
pwndbg> r
Starting program: /home/trap/a.out

Breakpoint 1, 0x0000555555555149 in main ()
Traceback (most recent call last):
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/hooks.py", line 32, in update_arch
    arch_mod.update()
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/arch.py", line 57, in update
    arch_name, ptrsize, endian = _get_arch(typeinfo.ptrsize)
  File "/home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/arch.py", line 37, in _get_arch
    arch = gdb.newest_frame().architecture().name()
gdb.error: Selected thread is running.

PS: Pull requests are welcome
> /home/(this_is_secret)/tools/pwndbg/pwndbg/gdblib/arch.py(37)_get_arch()
-> arch = gdb.newest_frame().architecture().name()
```
And I tested in GDB 10.2. 
In two version of GDB (10.2 and 13.1), same error is occurred.

**Comment by disconnect3d** [comment] 2023-04-06 09:21
Hmm this seems like either a bug with our events or a bug in GDB. Interestingly, this seems to work fine:
```py
import gdb

def exit_handler (event):
    print ("event type: exit")
    if hasattr (event, 'exit_code'):
        print ("exit code: %d" % (event.exit_code))
    else:
        print ("exit code not available")

gdb.events.exited.connect(exit_handler)

def stop_handler(event):
    print ("event type: stop", event, event.__dict__)
    print("gdb:", gdb.newest_frame().architecture().name())

gdb.events.stop.connect(stop_handler)

def cont_handler(event):
    print ("event type: cont", event, event.__dict__)
    print("gdb:", gdb.newest_frame().architecture().name())

gdb.events.cont.connect(cont_handler)
```

However, we are setting multiple events... Maybe GDB does not handle multiple events well and schedule/fire them incorrectly (e.g. after doing some internal state change that a thread is running).

On our side this can be somehow debugged with `set debug-events on` but I still doesn't understand this issue.

**Comment by disconnect3d** [comment] 2023-04-06 09:31
As @gsingh93 pointed out before, this is really a GDB bug that seems to come from the fact that we do `gdb.execute` in stop handlers. We had it reported back then in https://github.com/pwndbg/pwndbg/issues/425#issuecomment-486772229 and we reported it to GDB in https://sourceware.org/bugzilla/show_bug.cgi?id=29831.

I have hooked `gdb.execute` in GDB and here is more or less the events + execution stack trace:
```
Breakpoint 1, 0x000055555555463e in main ()
'stop' pwndbg.gdblib.events._start_stop (<gdb.BreakpointEvent object at 0x7fd418451660>,)
'stop' pwndbg.gdblib.regs.update_last (<gdb.BreakpointEvent object at 0x7fd418451660>,)
'stop' pwndbg.gdblib.stack.update (<gdb.BreakpointEvent object at 0x7fd418451660>,)
execute(('info auxv',), {'to_string': True})
'cont' pwndbg.gdblib.regs.update_last (<gdb.ContinueEvent object at 0x7fd3eaa03120>,)
'cont' pwndbg.ida.UpdateBreakpoints (<gdb.ContinueEvent object at 0x7fd3eaa03120>,)
'cont' pwndbg.ida.Auto_UnColor_PC (<gdb.ContinueEvent object at 0x7fd3eaa03120>,)
'cont' pwndbg.gdblib.hooks.memoize_on_cont (<gdb.ContinueEvent object at 0x7fd3eaa03120>,)
'cont' pwndbg.gdblib.prompt.reset_context_shown (<gdb.ContinueEvent object at 0x7fd3eaa03120>,)
execute(('info target',), {'to_string': True})
execute(('maintenance print target-stack',), {'to_string': True})
'stop' pwndbg.gdblib.stack.is_executable (<gdb.BreakpointEvent object at 0x7fd418451660>,)
'stop' pwndbg.ida.UpdateBreakpoints (<gdb.BreakpointEvent object at 0x7fd418451660>,)
'stop' pwndbg.ida.Auto_Color_PC (<gdb.BreakpointEvent object at 0x7fd418451660>,)
'stop' pwndbg.commands.ida.j (<gdb.BreakpointEvent object at 0x7fd418451660>,)
'stop' pwndbg.gdblib.hooks.update_typeinfo (<gdb.BreakpointEvent object at 0x7fd418451660>,)
execute(('show language',), {'to_string': True})
'stop' pwndbg.gdblib.hooks.update_arch (<gdb.BreakpointEvent object at 0x7fd418451660>,)
execute(('show endian',), {'to_string': True})
Traceback (most recent call last):
  File "/home/dc/pwndbg/pwndbg/gdblib/events.py", line 156, in caller
    func()
  File "/home/dc/pwndbg/pwndbg/gdblib/hooks.py", line 32, in update_arch
    arch_mod.update()
  File "/home/dc/pwndbg/pwndbg/gdblib/arch.py", line 57, in update
    arch_name, ptrsize, endian = _get_arch(typeinfo.ptrsize)
  File "/home/dc/pwndbg/pwndbg/gdblib/arch.py", line 37, in _get_arch
    arch = gdb.newest_frame().architecture().name()
gdb.error: Selected thread is running.
```

**Comment by disconnect3d** [comment] 2023-04-12 14:09
I am going to close this since this is a duplicate of #425.

As I said, this is a GDB bug and we can't do much here on the Python side of things.

As a workaround, instead of using `command` GDB scripting to execute stuff on your breakpoints, use the Python API as shown here: https://github.com/pwndbg/pwndbg/issues/425#issuecomment-1505338472 (`return False` from the `stop` method makes so that the breakpoint does not stop the execution after the `stop` logic is executed).

**Closed as completed by disconnect3d** 2023-04-12 14:09 UTC
Labels: bug
