### ISSUE TITLE
Add a cyclic -d --detect flag to find cyclic pattern offset in registers and stack memory

### ISSUE THREAD

**Issue by nthdeg** [pwndbg/pwndbg#2011] opened 2024-02-03 00:02 UTC
**EDIT by @disconnect3d: The purpose of this issue is to track a new feature: adding a `-d --detect` flag to `cyclic` command so that it looks up the pattern offsets in registers and memory and prints this info to the user.**

An offset finding function to auto detect the cyclic input in order to return the offset value.

gdb-peda has this feature (`pattern_offset 0xdeadbeef`) and would like to request this be implemented if possible.

ref:

              @nthdeg Added the `[filename]` argument to `cyclic` command in #2009.

So you can now do:
```
cyclic 100 input
run < input
cyclic -l 0xdeadbeef
```
(replace `0xdeadbeef` with some cyclic pattern value)

We still need some kind of `cyclic -d|--detect` to auto detect the cyclic pattern values in registers and/or stack though.

_Originally posted by @disconnect3d in https://github.com/pwndbg/pwndbg/issues/2007#issuecomment-1923976631_

**Comment by disconnect3d** [comment] 2024-02-03 12:54
Hi, I changed the title and added a first line to this issue to make it clear what we want to track here with this issue :).

**Comment by peace-maker** [comment] 2024-02-05 17:15
Seems like a duplicate of #1965

**Comment by disconnect3d** [comment] 2024-02-05 23:27
Oh, thanks for pointing out. Closing since its a duplicate.

**Closed as completed by disconnect3d** 2024-02-05 23:27 UTC
Labels: duplicate
