### ISSUE TITLE
Can the `regs` module support frame selection of gdb?

### ISSUE THREAD

**Issue by cebrusfs** [pwndbg/pwndbg#513] opened 2018-08-22 10:33 UTC
Currently, the `regs` will [fetch the latest frame of the current thread](https://github.com/pwndbg/pwndbg/blob/c188ed37f7fc882a02bcf7fd9897c3ef427c3944/pwndbg/regs.py#L252). Then, some part in `context` rely on the this. (For example, `nearpc` and `stack`). But [the source code displaying relies on the selected frame](https://github.com/pwndbg/pwndbg/blob/c188ed37f7fc882a02bcf7fd9897c3ef427c3944/pwndbg/commands/context.py#L211). This will make `context` command view be not consistent.

Change `regs` module to fetch the current frame will resolve the above issue. The cache clearing will be trigger by `before_prompt` handler, so everything looks good. However, there will be a new problem. 

pwndbg has a feature that it will highlight the changed register, and [only save the register in the current frame when stoping](https://github.com/pwndbg/pwndbg/blob/c188ed37f7fc882a02bcf7fd9897c3ef427c3944/pwndbg/regs.py#L427). If we support frame/thread changing, what kind of register should be considered as "changed"? and what kind of the old value should be saved? Issue #366 has some relevance discuss but it seems no more update.

Here's two possible direction,
1. Keep showing the register changed after hitting `next`/`step` commands. If the frame/thread changed, don't show the markers and until switching the window back.
2. Also, shows the different between the views. That is, if we move to the new frame/thread, then the marker will display the changed between the new view and the old view.

Which case is much be useful and make sense? Any idea?

**Comment by disconnect3d** [comment] 2018-09-12 00:47
@cebrusfs what is your opinion on that? :)

The best option would probably be having two modes of operation for that.
The easiest option to implement is probably highlighting changed registers even if they change between changing frames (I believe this will work out of the box).
On the other hand showing changed regs only on next/step is also useful...

Imho this is not *that big deal*, so I would go with the easiest solution unless someone really wants something different.

Can you send a PR solving this one way or another? It would be really nice to support frame selection.

**Comment by cebrusfs** [comment] 2018-09-14 15:54
@disconnect3d I think my proposal 1. is useful in most of cases. I will follow this design. Unfortunately, I just find out `pwndbg.regs.changed` does not work when start working on this issue.

It seems `pwndbg.regs.last` will be updated when gdb stop/continue, and always keep the latest value. But it is for memorizing the previous registers values and then generating the change list `pwndbg.regs.changed`. It should be something wrong. 
I am not very familiar with `pwndbg.events` and there is no comment about what situation will trigger those events. Could you please give me a hand in looking into this bug and then figuring out the root cause? Thanks.

**Comment by disconnect3d** [comment] 2018-09-14 15:59
Pwndbg.events are just wrappers for gdb events. I can't look at the code
right now but as far as I remember if you decorate a function with
particular event this function will be fired on this gdb event.

You could try adding some prints here and there or 'import pdb;
pdb.set_trace()' (or even ipdb instead of pdb, if you have it installed,
however ipdb might not always work here).

I will try to look on this issue in an hour or two.

**Comment by disconnect3d** [comment] 2018-09-14 18:10
Btw just to kill one of the possible causes: the problem is not done because of caching as `pi pwndbg.memoize.memoize.caching=False` changes nothing and the problem persists.

**Comment by disconnect3d** [comment] 2018-09-14 18:17
@cebrusfs I have tried to debug it a little bit but I can't find the cause. Probably the easiest way to go in here is to make a `git bisect <commit-when-it-worked>` and find out the commit that caused it to stop working.

EDIT: Not sure how much you are into git; so TLDR: Git bisect lets you to make a binary search over versions (git commits) and mark them as "working" and "not working". This lets you to find a version that broke particular feature. Afaik this can be even automated, but here, one have to do it manually.

**Comment by disconnect3d** [comment] 2019-04-21 13:45
@cebrusfs are you going to work on that?

After re-reading this issue I think that maybe we should *just disable highlighting changes and enhancements* when we are on anything else than the current frame.

Otherwise things might be tricky - for displaying the code we don't want to show that particular memory has "this value" as it can have different value than it had previously when the program was at given point. With highlighting the registers - it is uncertain what would be the best way here, so I'd skip highlighting it.

**Comment by cebrusfs** [comment] 2019-04-22 05:45
No. I am busy on my own stuff recently. It would be great if anyone can take over this.

**Comment by stnevans** [comment] 2019-06-02 05:02
@disconnect3d  did #636 address any of this?

**Comment by disconnect3d** [comment] 2019-06-05 10:48
We do support thread/frame changing and it seems we highlight registers that differs from latest frame (not sure if it's always from selected thread or cached).

I think this is good for now and we can close it.

**Closed as completed** 2019-06-11 01:37 UTC
Labels: enhancement, help wanted, feature, good first issue
