### ISSUE TITLE
Gdb tab auto complete broken by `import readline`

### ISSUE THREAD

**Issue by PandaWill** [pwndbg/pwndbg#2232] opened 2024-06-13 14:48 UTC
### Description
Gdb tab autocomplete is broken. It appears that `environ["PWNLIB_NOTERM"]=1` is the reason why.

It starts working if I remove this line: https://github.com/pwndbg/pwndbg/blob/bf091df52781de81b7d4662fc65ce18d11aeecb8/gdbinit.py#L59

### Steps to reproduce
Open Gdb, type `st<TAB>`

We expect it to show the options of "start", "step", etc. We get a literal tab.

### My setup
pwndbg> version
Gdb 12.1
Python: 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0]
Pwndbg: 2024.02.14 build: ffc09e57
Capstone: 5.0.1280
Unicorn: 2.0.1

**Comment by B1N4RY-P4R45173** [comment] 2024-06-13 17:43
I am still very new to this project. But I have noticed two things:
1) There are multiple commands starting with `st` so it cannot autocomplete. I am assuming u are referring to autocomplete suggestion?? I noticed that pressing the tab again displays all suggestions. Maybe a bug?? idk....

![image](https://github.com/pwndbg/pwndbg/assets/77494118/2b9674d1-77ea-4172-8d26-295e8b447173)

2) If you were actually referring to autocomplete then try `sto` and hitting tab key.  It should complete it to the word `stop`. Check if that works.

**Comment by PandaWill** [comment] 2024-06-13 18:23
Sorry, yes that's what I mean suggestions. I don't get the suggestions or autocomplete though.

Unless I comment out the `environ["PWNLIB_NOTERM"]=1` line (or set it to zero).

https://github.com/pwndbg/pwndbg/blob/bf091df52781de81b7d4662fc65ce18d11aeecb8/gdbinit.py#L59

**Comment by B1N4RY-P4R45173** [comment] 2024-06-13 19:26
I tried changing `PWNLIB_NOTERM` to `0`. It didn't seem to invoke any issues at the moment but according to

https://github.com/pwndbg/pwndbg/blob/bf091df52781de81b7d4662fc65ce18d11aeecb8/docs/env_vars.md?plain=1#L17

U might face issues with decencies that use pwntools. And did it work fine before https://github.com/pwndbg/pwndbg/commit/ffc09e57f3b870f99f52815b983ef678bf69636f ?

**Comment by disconnect3d** [comment] 2024-06-24 23:38
@PandaWill The autocompletion works for me no matter of the `PWNLIB_NOTERM` setting.

What distro, window manager and terminal do you use?

**Comment by PandaWill** [comment] 2024-06-25 10:00
Sorry, my initial diagnosis of this was misplaced.

I went on a wild ride of debugging, hacking out lots of code to find out what was breaking it.

I narrowed it down to the `import pdb` inside construct, inside pyelftools.

It's because I've been using pdb++ (drop in replacement for pdb).

I'll take the issue up with those folks, I guess they need a similar environmental variable for: "I don't own the terminal".

**Comment by disconnect3d** [comment] 2024-06-25 10:46
Thanks for looking into it! Please link the issue here once you open it on
their side :)

**Comment by PandaWill** [comment] 2024-06-27 16:07
They actually already have an option for this but it doesn't fix it because autocomplete is already broken by their import statements!

Namely fancycompleter, which imports rlcompleter, which imports readline.

Importing readline from the standard library is enough to break Gdb autocomplete.

You can see this by adding `import readline` to the gdbinit.py and it breaks autocomplete.

Presumably this is a horrible conflict between the CPython's and Gdb's use of readline. I have no idea how to fix it.

The same problem can be encountered if you use pwndbg exception debugging with `ipdb` installed:
https://github.com/pwndbg/pwndbg/blob/83cc8c57cf87409a4e7748abefd56bb31b4d9cd9/pwndbg/exception.py#L13

Although I can't see where ipdb would be importing readline, except within pdb itself: https://github.com/python/cpython/blob/main/Lib/pdb.py#L324

Regular pdb (not ipdb) doesn't break it, neither does using `IPython.embed()`. I'm not sure why.

**Comment by Aplet123** [comment] 2024-07-10 18:57
Python's `readline` module seems to do a lot of stuff on initialization (yuck) like rebinding tab to insert a literal tab, and ESC-TAB to use their completion function instead:

https://github.com/python/cpython/blob/3ec719fabf936ea7a012a76445b860759155de86/Modules/readline.c#L1296-L1299

**Comment by PandaWill** [comment] 2024-07-10 19:02
There is support in readline for saving and restoring state https://git.savannah.gnu.org/cgit/readline.git/tree/readline.c#n1459

But cpython is doing none of this, it just assumes it's the sole user of readline and blindly re-initializes everything!

I feel like this needs to be fixed in cpython! Any other project that (like Gdb) uses readline and embeds python will run into the same issue.

**Comment by Aplet123** [comment] 2024-07-10 19:05
I think a hacky solution could just be adding `python 'import sys; sys.modules["readline"] = None'` (or some more intelligent mock than `None`) into the start of `.gdbinit` to just prevent the module from loading, but this is pretty awful.

@PandaWill Thoughts on closing the issue because it's not really a pwndbg issue?

**Comment by PandaWill** [comment] 2024-07-10 19:35
I/we could add a test case that just imports pwndbg and checks for readline in sys.modules?

It'd be nice to have something to make sure we notice if it's accidentally broken in the future. Especially since it can be trivially broken by something deep down the dependency chain.

Also it would save somebody else from going down this rabbit hole in the future!

**Comment by disconnect3d** [comment] 2024-07-24 22:45
@PandaWill Yes, pls add a testcase for it with appropriate comments.

**Comment by disconnect3d** [comment] 2024-08-17 11:10
We now test that readline is never imported by us in #2375 :)

**Comment by mochaaP** [comment] 2024-10-14 10:58
broken by Python 3.13+ (`pdb.py` → `cmd.py` → `code.py` → `rlcompleter.py` → `readline.py`)

A possible temp fix is to add a stub:

```python
# $PWNDBG/rlcompleter.py
class Completer:
	pass
```

cc @disconnect3d any ideas for a better solution?

**Comment by disconnect3d** [comment] 2024-10-17 13:45
Reopening for Python 3.13+ case.

@mochaaP: To recap, if I understand correctly all what was said here, the problem is that readline is imported and configured in such a way that collides with GDB so tab auto complete stops working.

And this happens not on demand, when pdb is invoked, but during its import? This seems like a bug in CPython, since it will break other cases like this as well. Perhaps we should report it to CPython?

Maybe we could work around this by lazy importing pdb, only when its needed?

But we also override `pdb.set_trace` here, I wonder if we can drop this code safely..:

https://github.com/pwndbg/pwndbg/blob/dcc8db702183ceac7bb52e567b0e2141f02fc5d3/pwndbg/exception.py#L127-L136

**Comment by disconnect3d** [comment] 2024-12-05 00:26
@patryk4815 can u check this out on py 3.13 release?

**Comment by patryk4815** [comment] 2024-12-13 20:34
CPython implemented:
https://github.com/python/cpython/issues/112948
https://github.com/python/cpython/pull/112950
Because of that gdb is broken after `import pdb` :(

**Comment by patryk4815** [comment] 2024-12-13 23:57
Since Python 3.4, the `find_loader()` and `find_module()` APIs have been deprecated, and as of Python 3.12, they have been officially removed. This change is documented in [GH-98040](https://github.com/python/cpython/issues/98040)

GDB relies on these deprecated methods to disable the readline module, as demonstrated in the following code section:
[py-gdb-readline.c (L98-L111)](https://github.com/bminor/binutils-gdb/blob/62e4d4d3ad68fe17113069b99d80a9ee9df87cb1/gdb/python/py-gdb-readline.c#L98-L111)

Additionally there was another bug with:
`sys.meta_path.append(GdbRemoveReadlineFinder())`
should be changed to: `sys.meta_path.insert(0, GdbRemoveReadlineFinder())`

So we have to report this upstream gdb.

Bugzilla ticket: https://sourceware.org/bugzilla/show_bug.cgi?id=32473

**Comment by disconnect3d** [comment] 2024-12-15 16:00
Fixed in https://github.com/pwndbg/pwndbg/pull/2622

**Closed as completed** 2024-12-15 16:00 UTC
Labels: bug, upstream-bug
