### ISSUE TITLE
pwndb with rr integration - can't find the heap

### ISSUE THREAD

**Issue by n30m1nd** [pwndbg/pwndbg#316] opened 2017-08-03 08:56 UTC
As requested from issue [#294](https://github.com/pwndbg/pwndbg/issues/294#event-1190405813). Pwndbg fails to execute the `heap` command when running inside `rr` debugging session.
[![asciicast](https://asciinema.org/a/TxTOMZnFGHD4uuKsXgiYixZ2U.png)](https://asciinema.org/a/TxTOMZnFGHD4uuKsXgiYixZ2U)

In my opinion this is way out of pwndbg's scope but, if you could fully integrate pwndbg with rr, you'll make me happy :)

Setup:
* Linux LP5346436SP 4.9.4-040904-generic #201701150831 SMP Sun Jan 15 13:33:50 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
* Ubuntu 16.04.2 LTS
* Ubuntu GLIBC 2.23-0ubuntu9
* Python 2.7.12

**Comment by disconnect3d** [comment] 2017-08-12 12:14
@n30m1nd Hey,

Could you try diving more into the issue? Maybe there is something we can do?
I have made some analysis of the problem below.

All of the commands lie in `pwndbg/commands/` and most of them have a seperate file.
So the `heap` command and the output you get is here: https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/commands/heap.py#L64 

The `get_region` and most of the heap implementation lies in https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/heap/ptmalloc.py#L171.

I guess the `addr` is `None` (however would be nice to double check that).
So we are getting a heap memory page and then we get `self.mp` (which is a property) which gets `mp_` symbol address and dereferences it as `struct malloc_par` ([in here](https://github.com/pwndbg/pwndbg/blob/dev/pwndbg/heap/ptmalloc.py#L50)).

It is probably caused by different memory mappings when replaying a record.
Lets check this out for a simple binary compiled as `gcc -ggdb main.c`:
```c
#include <stdio.h>
#include <stdlib.h>
int* foo() { return malloc(100); }
void bar(int* x) { free(x); } 

int main() {
    int* y = foo();
    bar(y);
}
```

Here you can see `vmmap` command result for replayed (left) and just launched under gdb binary (both are at the same instruction) - https://i.gyazo.com/b0a8ca554595e19f03d0f31a3a124ccc.png.

As the `foo` function returns a `malloc`ed area, after `next` command there should be a heap memory page.
It seems the rr replaying doesn't provide us this info as you can see here:
https://i.gyazo.com/d2dbb9701a70d486c130340ab5563721.png

It doesn't have a single memory page of that heap size actually :/.

**Comment by disconnect3d** [comment] 2018-05-04 09:42
We are not going to support heap stuff when using rr for now so I am closing it.

If anyone is willing to help, feel free to reply so I can assign you to this task and reopen it.

**Closed as completed by disconnect3d** 2018-05-04 09:42 UTC
Labels: help wanted, wontfix
