### ISSUE TITLE
gdbserver: Unable to access 16000 bytes of target memory

### ISSUE THREAD

**Issue by yooo1999** [pwndbg/pwndbg#1618] opened 2023-03-09 20:34 UTC
I tried to search some string into libc section with pwndbg (connecting to gdb-server):

`search -t string "GNU C Library" /lib/libc-2.23.so`

In `porc/PID/maps` I can see
```
757b0000-758db000 r-xp 00000000   /lib/libc-2.23.so
758db000-758ea000 ---p 0012b000 /lib/libc-2.23.so
758ea000-758ec000 r--p 0012a000  /lib/libc-2.23.so
758ec000-758ed000 rw-p 0012c000 /lib/libc-2.23.so
```

There are 2 bugs:
1: gdbserver I  see
```
gdbserver: Unable to access 16000 bytes of target memory at 0x757b3e8d, halting search.
gdbserver: Unable to access 16000 bytes of target memory at 0x758dee8d, halting search.
```

2:
The search didn't find the string even I know that string located at offset 0x11A2A4 in /lib/libc-2.23.so

**Comment by disconnect3d** [comment] 2023-03-09 22:12
Hi,

1. The `"Unable to access ... bytes of target memory at ..., halting search"` [is a warning printed out by GDB/GDBServer](https://github.com/bminor/binutils-gdb/blob/1478a11d76dbd4de9a0de43b1ea736223b3662c2/gdbsupport/search.cc#L52-L55) and we can't really suppress it. The warning also makes sense: for example, the `0x757b3e8d` address must be the last address of the executable mapping made with `mmap` to map the `libc-2.23.so` library. A similar thing happens in the next warning.

2. The search did not find anything because you are looking for a null-terminated string. This isn't documented properly in the `help search` (or `search --help`) but `-t string` makes the `search` command to look for a null terminated string. However... if you execute such search, you can see what data is exactly being looked for:
```
pwndbg> search -t string "GNU C Library"
Searching for value: b'GNU C Library\x00'
```
(We can see the `\x00` at the end which means we also look for the null byte)

What you can do instead, is to either not specify any type and let the `search` command to figure it out by itself (which may not always result in exactly what you want) or you can use the `-t bytes` type:

```
pwndbg> search -t bytes "GNU C Library"
Searching for value: 'GNU C Library'
libc-2.27.so    0x7ffff79756e0 push rbp

pwndbg> search "GNU C Library"
Searching for value: 'GNU C Library'
libc-2.27.so    0x7ffff79756e0 push rbp

pwndbg> x/s 0x7ffff79756e0
0x7ffff79756e0 <banner>:	"GNU C Library (Ubuntu GLIBC 2.27-3ubuntu1.6) stable release version 2.27.\nCopyright (C) 2018 Free Software Foundation, Inc.\nThis is free software; see the source for copying conditions.\nThere is NO wa"...

pwndbg> vmmap 0x7ffff79756e0
LEGEND: STACK | HEAP | CODE | DATA | RWX | RODATA
             Start                End Perm     Size Offset File
    0x7ffff77ba000     0x7ffff79a1000 r-xp   1e7000      0 /lib/x86_64-linux-gnu/libc-2.27.so +0x1bb6e0
```

The `search` finds the string at the `0x7ffff79756e0` address. It also shows there is `push rbp` at this address and this is because that address lies in an executable memory. We should maybe improve that display here, but anyway, the thing was found.
 
Hope this helps! I am going to close this issue since there is no actual bug in Pwndbg. 

Also:
* Regarding the `search` command, we have a GH issue to [improve its UX further](https://github.com/pwndbg/pwndbg/issues/1185)
* Regarding GDB warning... I will either report a bug/feature request about this to [GDB bugtracker](https://sourceware.org/bugzilla/) or just write to one of their [mailing lists](https://www.sourceware.org/gdb/mailing-lists/)

PS: In the future, please include all your GDB log in the issue as well as any other relevant information. For example, you could have done something like `x/s 0x 757b0000+0x11A2A4` to show us if the string you were looking for is really in the libc memory page and can be fetched by GDB. It is also good to include the output of the `version` command :).

**Comment by neryaz** [comment] 2023-03-09 22:51
@disconnect3d about 2.
no.
I didn't looking for  a null-terminated string.
that string is 
`GNU C Library (gcc- ........`
After GNU C Library there is no null-terminated 

so 
```
search -t string "GNU C Library" /lib/libc-2.23.so
search -t bytes "GNU C Library" /lib/libc-2.23.so
```
didn't works for me 
But when I press
`pwndbg> x/s 0x758ca2a4 #0x757b0000 + 0x11A2A4`
I can see the string

**Comment by yooo1999** [comment] 2023-03-09 22:51
@disconnect3d about 2.
no.
I didn't looking for  a null-terminated string.
that string is 
`GNU C Library (gcc- ........`
After GNU C Library there is no null-terminated 

so 
```
search -t string "GNU C Library" /lib/libc-2.23.so
search -t bytes "GNU C Library" /lib/libc-2.23.so
```
didn't works for me 
But when I press
`pwndbg> x/s 0x758ca2a4 #0x757b0000 + 0x11A2A4`
I can see the string

**Comment by disconnect3d** [comment] 2023-03-09 23:24
@yooo1999 Are you using the latest Pwndbg? Can you show what `version` shows and also the output of `search` and `x/s`?

**Comment by yooo1999** [comment] 2023-03-09 23:46
@disconnect3d my version is a847cbba92e6628b330164a53461a65987bfdc72

output of search:
```
search -t string "GNU C Library" /lib/libc-2.23.so
    Searching for value: b'GNU C Library\x00'
```

```
pwndbg> search -t bytes "GNU C Library" /lib/libc-2.23.so
    Searching for value: 'GNU C Library'
```

x/s is long string the end with \x00 and start with 
`GNU C Library (gcc- `

maybe re-open that issue please

**Comment by disconnect3d** [comment] 2023-03-10 02:10
(You are still not showing the full picture; I'd expect you showing the output of commands, heh)

I can re-open this, but how do I test this out if I can't reproduce this?

**Comment by disconnect3d** [comment] 2023-03-10 02:13
Hmm interesting: it seems that 0x757b0000+0x11A2A4 lies in the first memory page:
```
757b0000-758db000 r-xp 00000000   /lib/libc-2.23.so
```
but then we might have stopped looking for this because of GDB warning:
```
gdbserver: Unable to access 16000 bytes of target memory at 0x757b3e8d, halting search.
```

**Comment by disconnect3d** [comment] 2023-03-10 02:19
Hmm I wonder if this can be related to a GDB bug: https://github.com/pwndbg/pwndbg/issues/808

**Comment by disconnect3d** [comment] 2023-03-10 02:20
Can you see if things work for u with `set remote search-memory-packet off` or  `on`?

**Comment by disconnect3d** [comment] 2023-03-10 02:20
Also what GDB/GDBServer version do u have?

**Comment by disconnect3d** [comment] 2023-03-10 03:25
Fwiw @gsingh93 we removed that `set remote search-memory-packet off` setting in 77380eb63c6cfdb721f2a2c4448f9d544fa03bd7 🤐

**Comment by disconnect3d** [comment] 2023-03-10 03:32
I can confirm this bug happening on GDB 9.2, but not on GDB 10.2.

```
pwndbg> version
Gdb:      9.2
Python:   3.8.10 (default, Nov 14 2022, 12:59:47)  [GCC 9.4.0]
Pwndbg:   1.1.1 build: a3f12bc
Capstone: 4.0.1024
Unicorn:  2.0.1

pwndbg> search "GNU C"
Searching for value: 'GNU C'

pwndbg> set remote search-memory-packet off

pwndbg> search "GNU C"
Searching for value: 'GNU C'
libc-2.31.so    0x7ffff7f85b80 0x694c204320554e47 ('GNU C Li')
libc-2.31.so    0x7ffff7f85c9e 'GNU CC version 9.3.0.\nlibc ABIs: UNIQUE IFUNC ABSOLUTE\nFor bug reporting instructions, please see:\n<https://bugs.launchpad.net/ubuntu/+source/glibc/+bugs>.\n'
```

**Comment by disconnect3d** [comment] 2023-03-10 03:43
@yooo1999 This should be fixed by https://github.com/pwndbg/pwndbg/pull/1619 which was merged to the dev branch.

Please let us know if this works for you and sorry for the trouble! (We had this figured out before, but we removed this code, likely by mistake).

**Closed as completed** 2023-03-10 03:43 UTC
Labels: invalid

**Comment by yooo1999** [comment] 2023-03-10 08:05
@disconnect3d 
Still same problem
```
GNU gdbserver (GDB) 7.10

gdb-multiarch --version
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
```


When I set
`set remote search-memory-packet off`
I got
```
Searching for value: b'GNU C Library\x00'
warning: Unable to access 16000 bytes of target memory at 0xXXXXXX, halting search.
```

when I set
`set remote search-memory-packet on`
I just got
`Searching for value: b'GNU C Library\x00'`

pwndbg version:
git show
commit be306da2553596443d2bdaa378bf11cf59e3eab5 (HEAD -> dev, origin/dev, origin/HEAD)

**Comment by yooo1999** [comment] 2023-03-11 20:07
@disconnect3d 
Still same problem
```
GNU gdbserver (GDB) 7.10

gdb-multiarch --version
GNU gdb (Ubuntu 12.0.90-0ubuntu1) 12.0.90
```


When I set
`set remote search-memory-packet off`
I got
```
Searching for value: b'GNU C Library\x00'
warning: Unable to access 16000 bytes of target memory at 0xXXXXXX, halting search.
```

when I set
`set remote search-memory-packet on`
I just got
`Searching for value: b'GNU C Library\x00'`

pwndbg version:
git show
commit be306da2553596443d2bdaa378bf11cf59e3eab5 (HEAD -> dev, origin/dev, origin/HEAD)

Maybe re-open that issue.

**Comment by disconnect3d** [comment] 2023-03-15 10:35
I can re-open but I am not sure how to debug this further. I would need you to do some debugging here: you would have to modify this code: https://github.com/pwndbg/pwndbg/blob/be306da2553596443d2bdaa378bf11cf59e3eab5/pwndbg/search.py#L50-L74

And here, you can add prints for:
* `print("VMMAP: %#x-%#x" % (start, end))` -- see what is the searched vmmap start, end
* `print("i.search_memory(%#x, %#x, %#x) % (start, length, searchfor))` - see how is this executed
* `print("search_memory result=%#x" % start)` - see what is `start` after `search_memory`

**Comment by disconnect3d** [comment] 2023-03-15 10:36
What I am also worried about is that your problem may come from old GDBServer. The `GNU gdbserver (GDB) 7.10` is pretty old and it may be that using a newer version would just fix your problem. Any chance you can test that too?

**Comment by yooo1999** [comment] 2023-04-17 06:20
@disconnect3d I tried now with gdbserver 12.1 and that works (by the way I still got `gdbserver: Unable to access 16000 bytes of target memory at XXXXXXXX, halting search.`,  ) 
with gdbserver 7.10 still same problem but I guess it's doesn't important because it's old version
